extends Camera2D
## Camera Follow - Smooth follow with bounds
## Generated by Quantum Framework

@export var follow_target: NodePath
@export var smoothing_speed: float = 4.8
@export var use_bounds: bool = true
@export var bound_left: float = 0.0
@export var bound_top: float = 0.0
@export var bound_right: float = 5120.0
@export var bound_bottom: float = 432.0

var _shake_intensity: float = 0.0
var _shake_timer: float = 0.0
var _base_offset: Vector2

func _ready():
	_base_offset = offset
	position_smoothing_enabled = true
	position_smoothing_speed = smoothing_speed

	if use_bounds:
		limit_left = int(bound_left)
		limit_top = int(bound_top)
		limit_right = int(bound_right)
		limit_bottom = int(bound_bottom)

func _process(delta: float):
	if _shake_timer > 0:
		_shake_timer -= delta
		offset = _base_offset + Vector2(
			randf_range(-_shake_intensity, _shake_intensity),
			randf_range(-_shake_intensity, _shake_intensity)
		)
	else:
		offset = _base_offset

func shake(intensity: float = 5.0, duration: float = 0.3):
	_shake_intensity = intensity
	_shake_timer = duration
