extends CanvasLayer
# HUD Manager - Tile-based SNES-style overlay
# Generated by Quantum Framework

var assets_sprites_hud_coin_icon_png: Texture2D
var assets_sprites_hud_item_box_png: Texture2D
var assets_sprites_hud_mario_text_png: Texture2D
var assets_sprites_hud_numbers_small_png: Texture2D
var assets_sprites_hud_time_text_png: Texture2D
var assets_sprites_hud_x_symbol_png: Texture2D

var coins: int = 0
var lives: int = 0
var time_left: int = 0
var score: int = 0
var yoshi_coins: int = 0

var _countdown_timer: float = 0.0
var _countdown_active: bool = true
var _hurry_mode: bool = false
var _hurry_flash_timer: float = 0.0
var _bonus_countdown_active: bool = false
var _bonus_countdown_timer: float = 0.0
var _course_clear: bool = false
var _canvas: Control
var _tint_yellow: Color = Color(1, 1, 0, 1)

func _ready():
	assets_sprites_hud_coin_icon_png = load("res://assets/sprites/hud_coin_icon.png")
	assets_sprites_hud_item_box_png = load("res://assets/sprites/hud_item_box.png")
	assets_sprites_hud_mario_text_png = load("res://assets/sprites/hud_mario_text.png")
	assets_sprites_hud_numbers_small_png = load("res://assets/sprites/hud_numbers_small.png")
	assets_sprites_hud_time_text_png = load("res://assets/sprites/hud_time_text.png")
	assets_sprites_hud_x_symbol_png = load("res://assets/sprites/hud_x_symbol.png")
	_canvas = Control.new()
	_canvas.set_anchors_preset(Control.PRESET_FULL_RECT)
	_canvas.connect("draw", _on_draw)
	add_child(_canvas)

func _process(delta: float):
	if _countdown_active:
		_countdown_timer += delta
		if _countdown_timer >= 1.0:
			_countdown_timer -= 1.0
			time_left = max(0, time_left - 1)
			if time_left == 100:
				_hurry_mode = true
				QuantumEventBus.emit_event("time-hurry", {})
	if _hurry_mode:
		_hurry_flash_timer += delta
	if _bonus_countdown_active:
		_bonus_countdown_timer += delta
		if _bonus_countdown_timer >= 0.02:
			_bonus_countdown_timer -= 0.02
			if time_left > 0:
						time_left -= 1
	if time_left == 100:
		QuantumEventBus.emit_event("time-hurry", {})
	if time_left <= 0:
		QuantumEventBus.emit_event("time-up", {})
	_canvas.queue_redraw()

func _on_draw():

	_canvas.draw_texture(assets_sprites_hud_item_box_png, Vector2(112, 0))
	_canvas.draw_texture(assets_sprites_hud_mario_text_png, Vector2(16, 8))
	_canvas.draw_texture(assets_sprites_hud_time_text_png, Vector2(152, 8))
	_canvas.draw_texture(assets_sprites_hud_x_symbol_png, Vector2(24, 16))

	_draw_counter_right(coins, 232, 8, assets_sprites_hud_coin_icon_png, assets_sprites_hud_x_symbol_png, 8, 8, _tint_yellow)
	_draw_number_tinted(lives, 32, 16, 2, 8, 8, _tint_yellow)
	if _hurry_mode and int(_hurry_flash_timer * 4) % 2 == 0:
		_draw_number_tinted(time_left, 152, 16, 3, 8, 8, Color(1, 0.2, 0.2, 1))
	else:
		_draw_number_tinted(time_left, 152, 16, 3, 8, 8, _tint_yellow)
	_draw_number_right(score, 232, 16, 8, 8, _tint_yellow)

	for i in range(yoshi_coins):
		_canvas.draw_texture(assets_sprites_hud_coin_icon_png, Vector2(64 + i * 8, 16))

	if _course_clear:
		_draw_course_clear()

func _draw_number(value: int, x: int, y: int, digits: int, dw: int, dh: int):
	var s = str(value)
	while s.length() < digits:
			s = "0" + s
	for i in range(s.length()):
			var digit = s[i].to_int()
			var src_rect = Rect2(digit * dw, 0, dw, dh)
			var dst_rect = Rect2(x + i * dw, y, dw, dh)
			_canvas.draw_texture_rect_region(assets_sprites_hud_numbers_small_png, dst_rect, src_rect)

func _draw_number_tinted(value: int, x: int, y: int, digits: int, dw: int, dh: int, tint: Color):
	var s = str(value)
	while s.length() < digits:
			s = "0" + s
	for i in range(s.length()):
			var digit = s[i].to_int()
			var src_rect = Rect2(digit * dw, 0, dw, dh)
			var dst_rect = Rect2(x + i * dw, y, dw, dh)
			_canvas.draw_texture_rect_region(assets_sprites_hud_numbers_small_png, dst_rect, src_rect, tint)

func _draw_number_right(value: int, right_x: int, y: int, dw: int, dh: int, tint: Color):
	var s = str(value)
	var start_x = right_x - s.length() * dw
	for i in range(s.length()):
			var digit = s[i].to_int()
			var src_rect = Rect2(digit * dw, 0, dw, dh)
			var dst_rect = Rect2(start_x + i * dw, y, dw, dh)
			_canvas.draw_texture_rect_region(assets_sprites_hud_numbers_small_png, dst_rect, src_rect, tint)

func _draw_counter_right(value: int, right_x: int, y: int, icon: Texture2D, sym: Texture2D, dw: int, dh: int, tint: Color):
	var s = str(value)
	var digits_w = s.length() * dw
	var sym_x = right_x - digits_w - dw
	var icon_x = sym_x - dw
	_canvas.draw_texture(icon, Vector2(icon_x, y))
	_canvas.draw_texture(sym, Vector2(sym_x, y))
	var start_x = right_x - digits_w
	for i in range(s.length()):
			var digit = s[i].to_int()
			var src_rect = Rect2(digit * dw, 0, dw, dh)
			var dst_rect = Rect2(start_x + i * dw, y, dw, dh)
			_canvas.draw_texture_rect_region(assets_sprites_hud_numbers_small_png, dst_rect, src_rect, tint)

func _draw_course_clear():
	var screen_size = _canvas.size
	_canvas.draw_rect(Rect2(0, 0, screen_size.x, screen_size.y), Color(0, 0, 0, 0.7))
	# Course clear text would use a sprite in production

func update_label(label_name: String, value):
	match label_name:
			"coins":
				coins = int(value)
				while coins >= 100:
					coins -= 100
					lives += 1
			"lives":
				lives = int(value)
			"time_left":
				time_left = int(value)
			"score":
				score = int(value)
			"yoshi_coins":
				yoshi_coins = int(value)

func set_time(value: int):
	time_left = value

func stop_timer():
	_countdown_active = false

func start_bonus_countdown():
	_countdown_active = false
	_bonus_countdown_active = true

func show_course_clear():
	_course_clear = true
