extends CharacterBody2D
## Player Controller - SMW-style platformer physics
## Generated by Quantum Framework

@export var move_speed: float = 90.0
@export var jump_velocity: float = -280.9
@export var gravity_up: float = 600.0
@export var gravity_down: float = 1050.0
@export var jump_hold_boost: float = 50.0
@export var coyote_frames: int = 6
@export var max_fall_speed: float = 240.0

var _coyote_counter: int = 0
var _jump_held: bool = false
var _facing_right: bool = true
var _stomp_bouncing: bool = false

# Death state
var is_dead: bool = false
var _death_texture: Texture2D = null
var _normal_texture: Texture2D = null

# Animation
var _anim_timer: float = 0.0
var _walk_frames: Array = [1, 2, 3]
var _walk_frame_idx: int = 0
var _walk_speed: float = 0.18
var _idle_frame: int = 0
var _jump_frame: int = 4

func _ready():
	collision_layer = 1
	collision_mask = 3
	floor_max_angle = deg_to_rad(70.0)
	floor_snap_length = 4.0
	floor_block_on_wall = true
	max_slides = 6

func _physics_process(delta: float):
	# Death: only apply gravity and slide
	if is_dead:
		velocity.y += gravity_down * delta
		move_and_slide()
		return

	# Enemy hit cooldown
	if _enemy_hit_cooldown > 0:
		_enemy_hit_cooldown -= delta

	# Gravity
	if not is_on_floor():
		var grav = gravity_down if velocity.y > 0 else gravity_up
		velocity.y += grav * delta
		velocity.y = min(velocity.y, max_fall_speed)
		_coyote_counter -= 1
	else:
		if _stomp_bouncing:
			_stomp_bouncing = false
		else:
			velocity.y = 0
			_coyote_counter = coyote_frames

	# Jump
	if Input.is_action_just_pressed("jump") and _coyote_counter > 0:
		velocity.y = jump_velocity
		_jump_held = true
		_coyote_counter = 0
		print("[JUMP] vel_y=", velocity.y, " pos_y=", global_position.y)

	# Variable jump height
	if Input.is_action_just_released("jump") and velocity.y < 0:
		velocity.y *= 0.5
		_jump_held = false

	# Jump hold boost
	if _jump_held and Input.is_action_pressed("jump") and velocity.y < 0:
		velocity.y -= jump_hold_boost * delta

	# Horizontal movement
	var direction = Input.get_axis("move_left", "move_right")
	if direction:
		velocity.x = direction * move_speed
		_facing_right = direction > 0
	else:
		velocity.x = move_toward(velocity.x, 0, move_speed * 0.2)

	move_and_slide()
	_check_enemy_collisions()
	_update_animation(delta)

var _enemy_hit_cooldown: float = 0.0

func _check_enemy_collisions():
	if _enemy_hit_cooldown > 0:
		return
	for i in range(get_slide_collision_count()):
		var col = get_slide_collision(i)
		var collider = col.get_collider()
		if not collider or not collider.has_meta("tag"):
			continue
		var tag = collider.get_meta("tag")
		var normal = col.get_normal()
		if tag == "enemy":
			_enemy_hit_cooldown = 0.3
			QuantumEventBus.emit_event("enemy-collision", {
				"other": collider,
				"normal_y": normal.y
			})
			break
		elif tag == "qblock" and normal.y > 0.5:
			if collider.has_method("hit"):
				collider.hit()
			QuantumEventBus.emit_event("qblock-hit", {
				"other": collider,
				"normal_y": normal.y
			})
		elif tag == "rotating_block" and normal.y > 0.5:
			if collider.has_method("hit"):
				collider.hit()
			QuantumEventBus.emit_event("rotating-block-hit", {
				"other": collider,
				"normal_y": normal.y
			})

func die():
	if is_dead:
		return
	is_dead = true
	process_mode = Node.PROCESS_MODE_ALWAYS
	var sprite = get_node_or_null("Sprite2D")
	if sprite and _death_texture:
		_normal_texture = sprite.texture
		sprite.texture = _death_texture
		sprite.hframes = 1
		sprite.vframes = 1
		sprite.frame = 0
		sprite.flip_h = false
	velocity = Vector2(0, -200)
	set_deferred("collision_layer", 0)
	set_deferred("collision_mask", 0)

func set_death_texture(tex: Texture2D):
	_death_texture = tex

func stomp_bounce(vel: float):
	print("[STOMP_BOUNCE] before_vel_y=", velocity.y, " bounce_vel=", vel, " pos_y=", global_position.y)
	velocity.y = vel
	_jump_held = false
	_coyote_counter = 0
	_stomp_bouncing = true

func _update_animation(delta: float):
	var sprite = get_node_or_null("Sprite2D")
	if not sprite:
		return

	# Flip sprite based on facing direction
	# SMW spritesheets face LEFT by default, flip when facing right
	sprite.flip_h = _facing_right

	# Frame selection
	if not is_on_floor():
		# Airborne: jump frame
		sprite.frame = _jump_frame
		_anim_timer = 0.0
		_walk_frame_idx = 0
	elif abs(velocity.x) > 5:
		# Walking: cycle through walk frames
		_anim_timer += delta
		if _anim_timer >= _walk_speed:
			_anim_timer = 0.0
			_walk_frame_idx = (_walk_frame_idx + 1) % _walk_frames.size()
		sprite.frame = _walk_frames[_walk_frame_idx]
	else:
		# Idle
		sprite.frame = _idle_frame
		_anim_timer = 0.0
		_walk_frame_idx = 0


# --- Spin Jump (SMW-style) ---
var _is_spin_jumping: bool = false
var _spin_jump_velocity_mult: float = 0.85

func _unhandled_input(event):
	if event.is_action_pressed("spin_jump") and is_on_floor() and not is_dead:
		velocity.y = jump_velocity * _spin_jump_velocity_mult
		_is_spin_jumping = true
		_jump_held = true
		_coyote_counter = 0
		QuantumBridge.play_sound("sfx-spin")

func _check_spin_landing():
	if _is_spin_jumping and is_on_floor():
		_is_spin_jumping = false
		var sprite = get_node_or_null("Sprite2D")
		if sprite:
			sprite.rotation = 0.0

func _spin_visual(delta: float):
	if _is_spin_jumping:
		var sprite = get_node_or_null("Sprite2D")
		if sprite:
			sprite.rotation += delta * 20.0
