extends Node
## SceneManager — handles scene transitions and persistent state.
## Generated by Quantum Framework - Godot Backend

var persistent_state: Dictionary = {}
var current_scene_name: String = ""

var _transition_layer: CanvasLayer
var _color_rect: ColorRect
var _transitioning: bool = false

func _ready():
	_setup_transition_layer()
	_init_persistent_state()


func _setup_transition_layer():
	_transition_layer = CanvasLayer.new()
	_transition_layer.layer = 100
	add_child(_transition_layer)
	_color_rect = ColorRect.new()
	_color_rect.color = Color.BLACK
	_color_rect.anchors_preset = Control.PRESET_FULL_RECT
	_color_rect.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_color_rect.modulate.a = 0.0
	_transition_layer.add_child(_color_rect)

func transition_to(scene_name: String, effect: String = "fade", duration: float = 0.5, data: Dictionary = {}):
	if _transitioning:
		return
	_transitioning = true
	for key in data:
		persistent_state[key] = data[key]
	var scene_path = "res://scenes/" + scene_name + ".tscn"
	match effect:
		"fade":
			await _fade_out(duration / 2.0)
			get_tree().change_scene_to_file(scene_path)
			await get_tree().process_frame
			current_scene_name = scene_name
			await _fade_in(duration / 2.0)
		"iris-out":
			await _fade_out(duration)
			get_tree().change_scene_to_file(scene_path)
			await get_tree().process_frame
			current_scene_name = scene_name
			_color_rect.modulate.a = 0.0
		"iris-in":
			_color_rect.modulate.a = 1.0
			get_tree().change_scene_to_file(scene_path)
			await get_tree().process_frame
			current_scene_name = scene_name
			await _fade_in(duration)
		"cut":
			get_tree().change_scene_to_file(scene_path)
			await get_tree().process_frame
			current_scene_name = scene_name
	_transitioning = false

func _fade_out(duration: float):
	var tween = create_tween()
	tween.tween_property(_color_rect, "modulate:a", 1.0, duration)
	await tween.finished

func _fade_in(duration: float):
	var tween = create_tween()
	tween.tween_property(_color_rect, "modulate:a", 0.0, duration)
	await tween.finished

func set_state(key: String, value):
	persistent_state[key] = value

func get_state(key: String, default = null):
	return persistent_state.get(key, default)

func _init_persistent_state():
	persistent_state["lives"] = 5
	persistent_state["score"] = 0
	persistent_state["coins"] = 0
	persistent_state["yoshi_coins"] = 0
	persistent_state["levels_cleared"] = ""
