"""
Testing Engine - Python Code Templates

Provides:
  - TEST_TEMPLATE: Base template for generated pytest files
  - Reuses PyBuilder from terminal_templates
"""

from runtime.terminal_templates import PyBuilder, py_string, py_id


# ==========================================================================
# Test file template
# ==========================================================================

TEST_TEMPLATE = '''"""
{title} - Generated by Quantum Testing Engine
Run: pytest {filename} -v
Requires: pip install pytest playwright pytest-playwright
"""

import pytest
import json
import time
from unittest.mock import MagicMock, patch
{extra_imports}

{test_code}
'''

BROWSER_IMPORTS = """import re
from playwright.sync_api import Page, expect, BrowserContext
"""

ASYNC_BROWSER_IMPORTS = """import asyncio
from playwright.async_api import async_playwright, Page, expect, BrowserContext
"""


# ==========================================================================
# Helper code snippets embedded in generated tests
# ==========================================================================

FIXTURE_HELPER = '''
@pytest.fixture
def {name}({params}):
    """{docstring}"""
    {body}
'''

CONFTEST_TEMPLATE = '''"""
conftest.py - Generated by Quantum Testing Engine
"""

import pytest
from playwright.sync_api import sync_playwright

{fixtures}
'''


def sanitize_test_name(name: str) -> str:
    """Convert a human-readable test name to a valid Python identifier."""
    result = name.lower()
    result = result.replace(' ', '_').replace('-', '_').replace('.', '_')
    result = ''.join(c for c in result if c.isalnum() or c == '_')
    if result and result[0].isdigit():
        result = '_' + result
    return result


def sanitize_class_name(name: str) -> str:
    """Convert a suite name to a valid Python class name."""
    # Replace separators with spaces for splitting
    normalized = name.replace('-', ' ').replace('_', ' ')
    words = normalized.split()
    # Capitalize first letter of each word, preserve rest of casing
    result = ''.join(w[0].upper() + w[1:] if w else '' for w in words)
    # Remove non-alphanumeric chars
    result = ''.join(c for c in result if c.isalnum())
    if result and result[0].isdigit():
        result = 'Test' + result
    if not result.startswith('Test'):
        result = 'Test' + result
    return result
