"""
UI Engine - Desktop Templates

Provides templates for Python pywebview desktop apps with JS bridge:
  - QUANTUM_STATE_CLASS: Reactive state container with JS notification
  - QUANTUM_API_CLASS: API class template exposed to JavaScript
  - JS_BRIDGE_CODE: JavaScript bridge for Python-JS communication
  - DESKTOP_TEMPLATE: Complete Python pywebview app template
"""

from typing import Any, Dict


# ==========================================================================
# QuantumState Class - Reactive state container
# ==========================================================================

QUANTUM_STATE_CLASS = '''\
class QuantumState:
    """Reactive state container with JS notification."""

    def __init__(self, window_ref):
        self._window = window_ref
        self._state: Dict[str, Any] = {}

    def set(self, name: str, value: Any):
        """Set a state value and notify JS."""
        self._state[name] = value
        self._notify_js(name, value)

    def get(self, name: str, default: Any = None) -> Any:
        """Get a state value."""
        return self._state.get(name, default)

    def _notify_js(self, name: str, value: Any):
        """Push state update to JS."""
        if self._window:
            import json
            js_value = json.dumps(value)
            self._window.evaluate_js(
                f"window.__quantumStateUpdate('{name}', {js_value})"
            )
'''


# ==========================================================================
# QuantumAPI Class Template - API exposed to JavaScript
# ==========================================================================

QUANTUM_API_CLASS = '''\
class QuantumAPI:
    """API exposed to JavaScript via pywebview."""

    def __init__(self):
        self._window = None
        self.state = None

    def _set_window(self, window):
        """Initialize window reference and state."""
        self._window = window
        self.state = QuantumState(window)
        # State initialization
{state_init}

    def __set_state(self, args):
        """Internal: two-way binding from JS inputs."""
        name = args.get('name') if isinstance(args, dict) else None
        value = args.get('value') if isinstance(args, dict) else None
        if name:
            self.state.set(name, value)

{function_methods}
'''


# ==========================================================================
# JavaScript Bridge Code
# ==========================================================================

JS_BRIDGE_CODE = '''\
<script>
// Quantum Desktop Bridge
window.__quantumState = {};
window.__quantumBindings = {};

// Called by Python when state changes
window.__quantumStateUpdate = function(name, value) {
    window.__quantumState[name] = value;
    var bindings = window.__quantumBindings[name] || [];
    bindings.forEach(function(b) {
        if (b.type === 'text') b.el.textContent = value;
        else if (b.type === 'value') b.el.value = value;
        else if (b.type === 'html') b.el.innerHTML = value;
    });
};

// Register element to receive state updates
window.__quantumBind = function(elId, stateName, type) {
    var el = document.getElementById(elId);
    if (!el) return;
    if (!window.__quantumBindings[stateName]) {
        window.__quantumBindings[stateName] = [];
    }
    window.__quantumBindings[stateName].push({el: el, type: type || 'text'});
};

// Wrapper to call Python functions
window.__quantumCall = async function(fn, args) {
    if (window.pywebview && window.pywebview.api && window.pywebview.api[fn]) {
        return await window.pywebview.api[fn](args || {});
    } else {
        console.warn('Quantum: API not ready or function not found:', fn);
    }
};

// Form data collector
window.__quantumFormData = function(form) {
    var data = {};
    var formData = new FormData(form);
    formData.forEach(function(value, key) {
        data[key] = value;
    });
    return data;
};
</script>
'''


# ==========================================================================
# Desktop App Template
# ==========================================================================

DESKTOP_TEMPLATE = '''\
"""Quantum UI Desktop App - Generated pywebview Application

This file was generated by the Quantum UI Engine.
It creates a native desktop window using pywebview with
bidirectional Python-JS communication.
"""

import webview
from typing import Dict, Any


{quantum_state_class}


{quantum_api_class}


def main():
    """Main entry point for the desktop application."""
    html_content = {html_content}

    # Create API instance
    api = QuantumAPI()

    # Create window with API
    window = webview.create_window(
        title={title},
        html=html_content,
        width={width},
        height={height},
        js_api=api,
    )

    # Set window reference after creation
    def on_loaded():
        api._set_window(window)

    window.events.loaded += on_loaded

    # Start the application
    webview.start()


if __name__ == "__main__":
    main()
'''


# ==========================================================================
# Helper functions for code generation
# ==========================================================================

def escape_for_python_string(s: str) -> str:
    """Escape a string for use in a Python triple-quoted string."""
    # Replace backslashes first, then other special chars
    s = s.replace('\\', '\\\\')
    s = s.replace("'''", "\\'\\'\\'")
    return s


def indent_code(code: str, spaces: int = 8) -> str:
    """Indent each line of code by the specified number of spaces."""
    indent = ' ' * spaces
    lines = code.split('\n')
    return '\n'.join(indent + line if line.strip() else line for line in lines)
