"""Every ```xml block in docs/, and how each one is checked.

A block is checked with the real parser — or run, when the page shows its
result (**Output:** / **Error:** right after it; tests/docs/
test_guide_examples_run.py runs the guide's, this runs the rest). What a
block is, is said by the page, never guessed from failure:

- A whole file (`<q:component>`, `<q:application>`, `<q:job>`) parses as is.
- Anything else is the body of a `<q:component>` — the common case: a few
  statements or some markup.
- A `.test.q` file (`<q:test>`) is parsed as one; `test:` steps alone go
  inside a `<q:test>`.
- A fragment that only makes sense inside something else says so in the
  fence: ```xml fragment=action — see CONTEXTS for the names.
- A block that must NOT parse is followed by **Error:** `part of the message`
  (the guide's convention), or says ```xml error="part of the message".
- A block that is not Quantum at all is not ```xml: use ```text or ```html.

Pages listed in UNDER_REVIEW say on the page that their examples are not
checked; they are being replaced, and are reported, not checked.
"""

import pathlib
import re
from dataclasses import dataclass
from typing import Optional

REPO = pathlib.Path(__file__).resolve().parents[2]
DOCS = REPO / 'docs'
NS = 'xmlns:q="https://quantum.lang/ns"'
F = '`' * 3

# Pages that document things that do not exist (ui:tabs, q:validate,
# q:job-queue…) carry a visible "Under review" notice and are replaced by tested
# examples (the Cookbook) or a generated reference. They are listed here so the
# list can only shrink: test_docs_xml_blocks.py fails if a page gains the
# notice without being listed, or keeps it after leaving the list.
UNDER_REVIEW = {
    'ui/overview.md', 'ui/layout.md', 'ui/forms.md', 'ui/data-display.md', 'ui/feedback.md',
    'ui/navigation.md', 'ui/overlays.md', 'ui/advanced-components.md',
    'features/animations.md', 'features/theming.md', 'features/form-validation.md',
    'examples/advanced.md', 'examples/agents.md', 'examples/conditionals.md',
    'examples/forms-actions.md', 'examples/games.md', 'examples/queries.md', 'examples/ui-theming.md',
    'targets/html.md', 'targets/mobile.md', 'targets/terminal.md',
    'extensibility/plugins.md',
    # Hand-written catalogs of snippets that nothing runs; the Cookbook replaces them.
    'examples/authentication.md', 'examples/data-import.md', 'examples/functions.md',
    'examples/loops.md', 'examples/state-management.md', 'extensibility/packages.md',
    'tools/vscode-extension.md',
}
NOTICE = '::: danger Under review'

# THE GUARD: Quantum code on the site is tested. A ```xml block is allowed when
#   1. it is not a block at all but an import of a tested file
#      (<<< @/../examples/cookbook/…) — nothing to check here;
#   2. it is a guide block with a result (**Output:** / **Shows:** / **Error:**),
#      run by test_guide_examples_run.py;
#   3. its page is in PARSE_ONLY_PAGES: parsed, not run — a list that only
#      shrinks, as the guide's examples gain results or become recipes;
#   4. its page is generated from the code (the Reference) and parsed here;
# or its page says "Under review". Anything else fails CI.
PARSE_ONLY_PAGES = {
    'guide/actions.md', 'guide/ai.md', 'guide/authentication.md', 'guide/components.md',
    'guide/conditionals.md', 'guide/data-import.md', 'guide/files-and-mail.md',
    'guide/getting-started.md', 'guide/how-a-page-runs.md', 'guide/installation.md',
    'guide/loops.md', 'guide/project-structure.md', 'guide/query.md', 'guide/quick-start.md',
    'guide/services.md', 'guide/sessions.md', 'guide/state-management.md', 'guide/testing.md',
    'guide/ui.md', 'guide/why-quantum.md',
    # The home page's example: to become an import of a recipe with the home rewrite.
    'index.md',
}
GENERATED_MARKER = 'Generated by scripts/generate-reference.py'

# fragment=<name>: the context a fragment is parsed in. {body} is the block.
CONTEXTS = {
    'action': f'<q:component name="Doc" {NS}><q:action name="doc">{{body}}</q:action></q:component>',
    'knowledge': f'<q:component name="Doc" {NS}><q:knowledge name="doc">{{body}}</q:knowledge></q:component>',
    'agent': (f'<q:component name="Doc" {NS}><q:agent name="doc" model="phi3">'
              f'<q:instruction>x</q:instruction>{{body}}<q:execute task="x"/></q:agent></q:component>'),
    'llm': f'<q:component name="Doc" {NS}><q:llm name="doc" model="phi3">{{body}}</q:llm></q:component>',
    'game': f'<q:application id="doc" type="game" {NS}>{{body}}</q:application>',
    'scene': f'<q:application id="doc" type="game" {NS}><qg:scene name="doc">{{body}}</qg:scene></q:application>',
    'terminal': f'<q:application id="doc" type="terminal" {NS}>{{body}}</q:application>',
    'ui-app': f'<q:application id="doc" type="ui" {NS}>{{body}}</q:application>',
    'test': '<q:test name="doc" page="/">{body}</q:test>',
}

FENCE = re.compile(r'^' + F + r'xml(?P<meta>[^\n]*)\n(?P<xml>.*?)^' + F + r'[ \t]*$', re.S | re.M)
AFTER = re.compile(r'\s*\*\*(?P<kind>Output|Error|Shows):\*\*[ \t]*(?:`(?P<inline>[^`\n]+)`)?')


@dataclass
class Block:
    path: str            # relative to docs/
    line: int
    xml: str
    fragment: Optional[str]
    error: Optional[str]  # the block must fail with this text
    shown: Optional[str]  # Output / Shows: the page shows its result


def blocks():
    for doc in sorted(DOCS.rglob('*.md')):
        if 'node_modules' in doc.parts or '.vitepress' in doc.parts:
            continue
        rel = doc.relative_to(DOCS).as_posix()
        text = doc.read_text(encoding='utf-8')
        for m in FENCE.finditer(text):
            meta = m['meta']
            frag = re.search(r'\bfragment=([\w-]+)', meta)
            err = re.search(r'\berror="([^"]+)"', meta)
            after = AFTER.match(text, m.end())
            error = err.group(1) if err else None
            shown = None
            if after and after['kind'] == 'Error':
                error = error or after['inline'] or ''
            elif after:
                shown = after['kind']
            yield Block(rel, text[:m.start()].count('\n') + 1, m['xml'],
                        frag.group(1) if frag else None, error, shown)


def source(block: Block) -> str:
    body = re.sub(r'^\s*<\?xml[^>]*\?>\s*', '', block.xml.strip())
    if block.fragment:
        if block.fragment not in CONTEXTS:
            raise ValueError(f'unknown fragment={block.fragment} (known: {", ".join(CONTEXTS)})')
        return CONTEXTS[block.fragment].format(body=body)
    head = re.sub(r'^(?:\s*<!--.*?-->)*\s*', '', body, flags=re.S)
    if re.match(r'<q:(component|application|job)\b', head):
        return body
    if head.startswith('<q:test') or head.startswith('<test:'):
        return body if head.startswith('<q:test') else CONTEXTS['test'].format(body=body)
    return f'<q:component name="Doc" {NS}>\n{body}\n</q:component>'


def parse(block: Block):
    from quantum.core.parser import QuantumParser
    text = source(block)
    if re.match(r'(?:\s*<!--.*?-->)*\s*<q:test\b', text, re.S):
        from quantum.core.features.native_testing.src.parser import parse_test_source
        return parse_test_source(text)
    return QuantumParser(use_cache=False).parse(text)


def check(block: Block) -> Optional[str]:
    """None when the block is what the page says it is; otherwise the problem."""
    if block.path in UNDER_REVIEW:
        return None
    try:
        parse(block)
    except Exception as exc:  # noqa: BLE001 — any failure is the finding
        message = str(exc)
        if block.error is not None:
            if block.error in message:
                return None
            return f'fails, but not with {block.error!r}: {message.splitlines()[0][:100]}'
        return message.splitlines()[0]
    if block.error is not None and not runs_elsewhere(block):
        return f'parses, but the page says it fails with {block.error!r}'
    return None


def guard(block: Block) -> Optional[str]:
    """None when the block is one of the allowed kinds (see THE GUARD)."""
    if block.path in UNDER_REVIEW or runs_elsewhere(block) or block.path in PARSE_ONLY_PAGES:
        return None
    if GENERATED_MARKER in (DOCS / block.path).read_text(encoding='utf-8'):
        return None
    return ('Quantum code that nothing tests: import it from a tested file '
            '(<<< @/../examples/cookbook/...), give it a checked **Output:** in the guide, '
            'or mark the page Under review')


def parse_only_pages_in_use():
    """The PARSE_ONLY_PAGES that still have a block that is parsed and not run."""
    return {b.path for b in blocks() if b.path in PARSE_ONLY_PAGES and not runs_elsewhere(b)}


# -- quantum.config.yaml snippets ---------------------------------------------

YAML_FENCE = re.compile(r'^' + F + r'ya?ml[^\n]*\n(?P<text>.*?)^' + F, re.S | re.M)


def config_snippets():
    """(path, line, text) of every ```yaml block whose top-level keys include a config section."""
    import yaml
    from quantum.runtime.web_config import _KNOWN_SECTIONS
    for doc in sorted(DOCS.rglob('*.md')):
        if 'node_modules' in doc.parts or '.vitepress' in doc.parts:
            continue
        rel = doc.relative_to(DOCS).as_posix()
        if rel in UNDER_REVIEW:
            continue
        text = doc.read_text(encoding='utf-8')
        for m in YAML_FENCE.finditer(text):
            try:
                data = yaml.safe_load(m['text'])
            except yaml.YAMLError:
                data = None
            if isinstance(data, dict) and set(data) & _KNOWN_SECTIONS:
                yield rel, text[:m.start()].count('\n') + 1, m['text']


def config_problem(text: str, monkeypatch) -> Optional[str]:
    """What loading the snippet as quantum.config.yaml complains about — errors
    and the warnings about keys nothing reads (CFG-2, CFG-3, DB-7)."""
    import logging
    import yaml
    from quantum.core.config_env import expand_env
    from quantum.runtime.web_config import _validate_config

    # ${NAME} is set by whoever runs the app; a snippet is not wrong for using one.
    for name in set(re.findall(r'\$\{(\w+)', text)):
        monkeypatch.setenv(name, 'x')

    class Warnings(logging.Handler):
        def __init__(self):
            super().__init__(logging.WARNING)
            self.messages = []

        def emit(self, record):
            self.messages.append(record.getMessage())

    handler = Warnings()
    log = logging.getLogger('quantum')
    log.addHandler(handler)
    try:
        _validate_config(expand_env(yaml.safe_load(text)), 'quantum.config.yaml')
    except Exception as exc:  # noqa: BLE001
        return str(exc).replace('\n', ' ')
    finally:
        log.removeHandler(handler)
    return handler.messages[0] if handler.messages else None


def runs_elsewhere(block: Block) -> bool:
    """The guide's examples with a result are RUN by test_guide_examples_run.py.

    There an **Error:** is usually a run-time error (a failed validation, a
    missing table) — the block parses, and that test checks it fails as shown.
    """
    return block.path.startswith('guide/') and (block.error is not None or block.shown is not None)
