"""Generate quantum_admin/INVENTORY.md by MEASURING the admin, never by hand.

    python scripts/admin-inventory.py

Step A1 of the plan to make the admin official: before moving anything to
declared services and .q screens, know what exists, what each route uses and
what actually responds. It measures:

  - FastAPI routes (quantum_admin/backend/main.py), from the AST: verb, path,
    area (tags), handler, lines, service modules the body uses.
  - Shadowed routes: asks Starlette's OWN router which route serves the URL
    of each one. If it is another one, this one is never reached.
  - Real status of each GET without parameters, authenticated, against a
    TEMPORARY database (QUANTUM_ADMIN_DATABASE_URL) — never the admin's real
    database. Write routes are not executed.
  - Backend service modules: lines, routes that use them, tests that cite them.
  - .q screens (quantum_admin/components/admin): route, require_auth, q:action,
    q:python blocks and what they touch, status — served from a temporary
    COPY of the repository layout, GET only.
"""

import ast
import collections
import logging
import os
import pathlib
import re
import shutil
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[1]
BACKEND = REPO / "quantum_admin" / "backend"
MAIN = BACKEND / "main.py"
SCREENS = REPO / "quantum_admin" / "components" / "admin"
OUTPUT = REPO / "quantum_admin" / "INVENTORY.md"
VERBS = {"get", "post", "put", "delete", "patch", "websocket"}
NOT_A_SERVICE = {"main", "schemas", "models", "database", "__init__", "run"}


# --------------------------------------------------------------------------- routes (AST)

def _import_map(tree):
    """local name -> backend module it came from (top level and inside functions)."""
    modules = {p.stem for p in BACKEND.glob("*.py")} | {p.stem for p in (REPO / "quantum_admin" / "core").glob("*.py")}
    mapping = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            base = node.module.split(".")[-1]
            if base in modules:
                for alias in node.names:
                    mapping[alias.asname or alias.name] = base
        elif isinstance(node, ast.Import):
            for alias in node.names:
                base = alias.name.split(".")[-1]
                if base in modules:
                    mapping[alias.asname or base] = base
    return mapping


def routes_from_ast():
    tree = ast.parse(MAIN.read_text(encoding="utf-8"))
    imports = _import_map(tree)
    routes = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        names = {n.id for n in ast.walk(node) if isinstance(n, ast.Name)}
        uses = sorted({imports[n] for n in names if n in imports} - NOT_A_SERVICE)
        effects = sorted(n for n in ("subprocess", "shutil", "open") if n in names)
        for dec in node.decorator_list:
            if not (isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute)
                    and isinstance(dec.func.value, ast.Name) and dec.func.value.id == "app"
                    and dec.func.attr in VERBS and dec.args
                    and isinstance(dec.args[0], ast.Constant)):
                continue
            tags = next((kw.value for kw in dec.keywords if kw.arg == "tags"), None)
            area = tags.elts[0].value if isinstance(tags, ast.List) and tags.elts else "—"
            html = any(kw.arg == "response_class" and getattr(kw.value, "id", "") == "HTMLResponse"
                       for kw in dec.keywords)
            routes.append({
                "verb": dec.func.attr.upper(), "path": dec.args[0].value, "area": area,
                "handler": node.name, "line": node.lineno,
                "lines": (node.end_lineno or node.lineno) - node.lineno + 1,
                "kind": "websocket" if dec.func.attr == "websocket" else ("page" if html else "api"),
                "uses": uses, "effects": effects,
            })
    return routes


# --------------------------------------------------------------------------- UI calls

_FETCH = re.compile(r"fetch\(\s*(?P<url>`[^`]*`|'[^']*'(?:\s*\+[^,)]*)?|\"[^\"]*\"(?:\s*\+[^,)]*)?|[A-Za-z_]\w*)"
                    r"(?P<rest>[^;]{0,300})")
_HX = re.compile(r"hx-(?P<verb>get|post|put|delete|patch)=\"(?P<url>[^\"]+)\"")
_HREF = re.compile(r"href=\"(?P<url>\{URL_PREFIX\}/[^\"#]*)\"")


def _normalize(url):
    """URL of a call in the HTML/JS generated by main.py -> example path, or None."""
    url = url.strip()
    if url[:1] not in "`'\"":
        return None                 # fetch(url) with a variable: not resolvable
    # '/docker/containers/' + id + '/start': each literal stays, each expression
    # between them becomes an example value.
    parts = []
    for piece in re.findall(r"`[^`]*`|'[^']*'|\"[^\"]*\"|[^+]+", url):
        piece = piece.strip()
        if not piece:
            continue
        parts.append(piece[1:-1] if piece[:1] in "`'\"" else "1")
    url = "".join(parts)
    url = url.replace("{URL_PREFIX}", "")
    url = re.sub(r"\$\{\{?[^}]*\}?\}", "1", url)       # ${x} and ${{x}} (inside an f-string)
    url = re.sub(r"\{\{?[^}]*\}?\}", "1", url)          # {project_id} from an f-string
    url = url.split("?")[0]
    return url if url.startswith("/") else None


def ui_calls():
    source = MAIN.read_text(encoding="utf-8")
    calls, dynamic = [], 0
    for m in _FETCH.finditer(source):
        path = _normalize(m.group("url"))
        if path is None:
            dynamic += 1
            continue
        verb = re.search(r"method\s*:\s*['\"`](\w+)", m.group("rest"))
        calls.append((verb.group(1).upper() if verb else "GET", path,
                      source[:m.start()].count("\n") + 1))
    for m in _HX.finditer(source):
        path = _normalize('"' + m.group("url") + '"')
        if path:
            calls.append((m.group("verb").upper(), path, source[:m.start()].count("\n") + 1))
    for m in _HREF.finditer(source):
        path = _normalize('"' + m.group("url") + '"')
        if path and not path.startswith("/static"):
            calls.append(("GET", path, source[:m.start()].count("\n") + 1))
    return calls, dynamic


# --------------------------------------------------------------------------- real app

def _example_url(path):
    return re.sub(r"\{[^}]+\}", "1", path)


def _serving_handler(candidates, verb, path):
    from starlette.routing import Match
    scope = {"type": "http", "path": path, "method": verb, "root_path": "",
             "query_string": b"", "headers": []}
    partial = None
    for candidate in candidates:
        match, _ = candidate.matches(scope)
        if match == Match.FULL:
            return getattr(getattr(candidate, "endpoint", None), "__name__", "?"), candidate.path
        if match == Match.PARTIAL and partial is None:
            partial = candidate.path
    return None, partial


def measure_app(routes):
    """Shadowing by the real router and status of the GETs without parameters."""
    tmp = pathlib.Path(tempfile.mkdtemp())
    os.environ["QUANTUM_ADMIN_DATABASE_URL"] = f"sqlite:///{(tmp / 'admin.db').as_posix()}"
    # The measured GETs create settings/global.yaml when it does not exist: in a
    # temporary folder, not the owner's.
    (tmp / "settings").mkdir()
    os.environ["QUANTUM_ADMIN_SETTINGS_DIR"] = str(tmp / "settings")
    os.environ["ADMIN_PASSWORD"] = "inventory-password-that-is-long-enough"
    os.environ["JWT_SECRET_KEY"] = "i" * 64
    for p in (str(REPO), str(REPO / "quantum_admin"), str(BACKEND)):
        if p not in sys.path:
            sys.path.insert(0, p)
    logging.disable(logging.CRITICAL)
    from starlette.routing import Match
    from starlette.testclient import TestClient
    from backend import main

    candidates = [r for r in main.app.routes if hasattr(r, "matches")]
    for route in routes:
        scope = {"type": "websocket" if route["verb"] == "WEBSOCKET" else "http",
                 "path": _example_url(route["path"]), "method": route["verb"],
                 "root_path": "", "query_string": b"", "headers": []}
        for candidate in candidates:
            match, _ = candidate.matches(scope)
            if match == Match.FULL:
                target = getattr(candidate, "endpoint", None)
                name = getattr(target, "__name__", "?")
                if name != route["handler"]:
                    route["shadowed_by"] = f"{name} ({candidate.path})"
                break

    # What the interface calls: each call resolved by the same router.
    calls, dynamic = ui_calls()
    called = collections.Counter()
    broken = []
    for verb, path, line in calls:
        handler, route_path = _serving_handler(candidates, verb, path)
        if handler:
            called[handler] += 1
        else:
            without_admin, _ = (_serving_handler(candidates, verb, path[len("/admin"):])
                                if path.startswith("/admin/") else (None, None))
            if without_admin:
                reason = f"exists without the `/admin` prefix (`{path[len('/admin'):]}` → `{without_admin}`)"
            elif route_path:
                reason = f"the route `{route_path}` exists, but does not accept {verb}"
            else:
                reason = "no route"
            broken.append((verb, path, line, reason))
    for route in routes:
        route["called_by_ui"] = called.get(route["handler"], 0)
    measurement = {"calls": len(calls), "dynamic": dynamic, "broken": broken}

    with TestClient(main.app, raise_server_exceptions=False) as client:
        login = client.post("/auth/login", params={"username": "admin",
                                                   "password": os.environ["ADMIN_PASSWORD"]})
        header = {"Authorization": f"Bearer {login.json()['access_token']}"}
        for route in routes:
            if route["verb"] != "GET" or "{" in route["path"] or route.get("shadowed_by"):
                continue
            try:
                response = client.get(route["path"], headers=header, follow_redirects=False)
                route["status"] = response.status_code
                if response.status_code >= 400:
                    route["detail"] = re.sub(r"\s+", " ", response.text)[:90]
            except Exception as exc:  # noqa: BLE001
                route["status"] = f"exception: {type(exc).__name__}"
    shutil.rmtree(tmp, ignore_errors=True)
    return measurement


# --------------------------------------------------------------------------- services

def service_modules(routes):
    tests = {p: p.read_text(encoding="utf-8", errors="replace")
             for p in (REPO / "tests").rglob("*.py")}
    screens = "\n".join(p.read_text(encoding="utf-8", errors="replace") for p in SCREENS.rglob("*.q"))
    usage = collections.Counter(m for r in routes for m in r["uses"])
    rows = []
    core = REPO / "quantum_admin" / "core"
    for file in sorted([*BACKEND.glob("*.py"), *core.glob("*.py")], key=lambda p: p.stem):
        name = file.stem
        if name in NOT_A_SERVICE:
            continue
        source = file.read_text(encoding="utf-8", errors="replace")
        if "sys.modules[__name__] = _module" in source:
            continue                     # a shim for a module that moved to core/ (A4.2)
        tree = ast.parse(source)
        public = [n.name for n in tree.body
                  if isinstance(n, (ast.FunctionDef, ast.ClassDef)) and not n.name.startswith("_")]
        cited = [str(p.relative_to(REPO)).replace("\\", "/") for p, t in tests.items()
                 if re.search(rf"\b{name}\b", t)]
        rows.append({"module": name, "lines": len(source.splitlines()), "public": len(public),
                     "routes": usage.get(name, 0), "tests": cited,
                     "q_screens": bool(re.search(rf"\b{name}\b", screens))})
    return rows


# --------------------------------------------------------------------------- .q screens

PY_EFFECTS = {
    "processes": r"\bsubprocess\b|\bPopen\b|os\.kill",
    "writes files": r"open\([^)]*['\"][wa]['\"]|save_yaml|write_text|shutil\.(copy|move)",
    "deletes": r"os\.remove|shutil\.rmtree|unlink\(",
    "reads files": r"open\(|load_yaml|os\.walk|glob\(|read_text",
    "network": r"\brequests\.|urllib|socket\.",
}


def q_screens():
    screens = []
    for file in sorted(SCREENS.rglob("*.q")):
        source = file.read_text(encoding="utf-8", errors="replace")
        rel = file.relative_to(SCREENS.parent).with_suffix("").as_posix()
        url = "/" + (rel[:-len("/index")] if rel.endswith("/index") else rel)
        blocks = re.findall(r"<q:python\b[^>]*>(.*?)</q:python>", source, re.S)
        code = "\n".join(blocks)
        screens.append({
            "file": str(file.relative_to(REPO)).replace("\\", "/"), "url": url,
            "auth": bool(re.search(r"<q:component[^>]*require_auth=\"true\"", source)),
            "actions": re.findall(r"<q:action\s+name=\"([^\"]+)\"", source),
            "python": len(blocks), "python_lines": sum(len(b.strip().splitlines()) for b in blocks),
            "effects": [name for name, pattern in PY_EFFECTS.items() if re.search(pattern, code)],
            "datasource": sorted(set(re.findall(r"datasource=\"([^\"]+)\"", source))),
            "yaml": sorted(set(re.findall(r"(?:load_yaml|save_yaml)\(\s*['\"]([^'\"]+)['\"]", code))),
            "services": sorted(set(re.findall(r"service=\"([^\"]+)\"", source))),
        })
    return screens


def measure_screens(screens):
    """GET on each screen, without login, served the way `quantum admin` serves it (data in a tmp)."""
    tmp = pathlib.Path(tempfile.mkdtemp())
    previous = os.getcwd()
    os.chdir(tmp)
    try:
        from quantum.cli import admin as cmd
        from quantum.runtime.web_server import QuantumWebServer
        config = cmd.prepare(str(tmp / "data"), str(tmp), 8090)
        client = QuantumWebServer(str(config)).app.test_client()
        for screen in screens:
            url = screen["url"].replace("[name]", "blog").replace("[...path]", "components/admin/dashboard.q")
            screen["status"] = client.get(url).status_code
    finally:
        os.chdir(previous)
        shutil.rmtree(tmp, ignore_errors=True)


# --------------------------------------------------------------------------- markdown

def write(routes, modules, screens, ui):
    by_area = collections.defaultdict(list)
    for r in routes:
        by_area[r["area"]].append(r)
    measured_gets = [r for r in routes if "status" in r]
    ok = sum(1 for r in measured_gets if isinstance(r["status"], int) and r["status"] < 400)
    shadowed = [r for r in routes if r.get("shadowed_by")]
    no_auth = [t for t in screens if not t["auth"]]
    L = []
    w = L.append
    w("# Quantum Admin Inventory")
    w("")
    w("> **Generated** by `python scripts/admin-inventory.py` — do not edit by hand. Measured, not "
      "declared: routes read from the AST of `quantum_admin/backend/main.py`, shadowing asked of "
      "the real router, status of each authenticated GET against a temporary database, `.q` screens "
      "served from a temporary copy. Write routes are not executed.")
    w("")
    w(f"**{len(routes)} FastAPI routes** in {len(by_area)} areas · "
      f"{sum(1 for r in routes if r['kind'] == 'page')} HTML pages · "
      f"{len(shadowed)} shadowed (never reached) · "
      f"GETs without parameters measured: {ok}/{len(measured_gets)} respond without error · "
      f"**{len(modules)} service modules** · **{len(screens)} `.q` screens**, "
      f"{len(no_auth)} without `require_auth`, {sum(t['python'] for t in screens)} `q:python` blocks.")
    w("")
    not_called = [r for r in routes if r["kind"] == "api" and not r["called_by_ui"]
                  and not r.get("shadowed_by")]
    w(f"The admin interface (HTML and JS generated inside `main.py`) makes **{ui['calls']} calls** "
      f"with a readable URL ({ui['dynamic']} use a variable and are not counted). "
      f"**{len(ui['broken'])} reach no route at all**. "
      f"**{len(not_called)} API routes are not called by the interface** — candidates to "
      f"go if they also serve nothing outside it (A2).")
    w("")
    w("## Areas")
    w("")
    w("| Area | Routes | Pages | Write | Called by the UI | Services used | GETs measured ok |")
    w("|---|---:|---:|---:|---:|---|---|")
    for area, rs in sorted(by_area.items(), key=lambda kv: -len(kv[1])):
        measured = [r for r in rs if "status" in r]
        good = sum(1 for r in measured if isinstance(r["status"], int) and r["status"] < 400)
        services = sorted({m for r in rs for m in r["uses"]})
        w(f"| {area} | {len(rs)} | {sum(1 for r in rs if r['kind'] == 'page')} | "
          f"{sum(1 for r in rs if r['verb'] in ('POST', 'PUT', 'DELETE', 'PATCH'))} | "
          f"{sum(1 for r in rs if r['called_by_ui'])} | "
          f"{', '.join(services) or '—'} | {f'{good}/{len(measured)}' if measured else '—'} |")
    w("")
    if shadowed:
        w("## Shadowed routes")
        w("")
        w("Declared, but the router hands the URL to another route registered earlier. Their "
          "code never runs.")
        w("")
        w("| Verb | Path | Handler (line) | Served by |")
        w("|---|---|---|---|")
        for r in shadowed:
            w(f"| {r['verb']} | `{r['path']}` | `{r['handler']}` ({r['line']}) | {r['shadowed_by']} |")
        w("")
    if ui["broken"]:
        w("## Interface calls that reach no route")
        w("")
        w("Buttons and screens that call a URL the router does not serve: they always fail.")
        w("")
        w("| Verb | Called URL | Line in main.py | Why |")
        w("|---|---|---:|---|")
        for verb, path, line, reason in sorted(set(ui["broken"]), key=lambda q: q[2]):
            w(f"| {verb} | `{path}` | {line} | {reason} |")
        w("")
    failures = [r for r in measured_gets if not (isinstance(r["status"], int) and r["status"] < 400)]
    if failures:
        w("## GETs that respond with an error")
        w("")
        w("| Path | Status | Response |")
        w("|---|---|---|")
        for r in failures:
            w(f"| `{r['path']}` | {r['status']} | {r.get('detail', '').replace('|', '/')} |")
        w("")
    w("## Service modules")
    w("")
    w("What the plan (A1) keeps as a library. **Routes** = routes whose handler uses the module; "
      "**tests** = test files that cite it.")
    w("")
    w("| Module | Lines | Public | Routes | .q screens | Tests |")
    w("|---|---:|---:|---:|---|---|")
    for m in sorted(modules, key=lambda m: -m["lines"]):
        tests = ", ".join(f"`{t.split('/')[-1]}`" for t in m["tests"][:3])
        if len(m["tests"]) > 3:
            tests += f" +{len(m['tests']) - 3}"
        w(f"| `{m['module']}` | {m['lines']} | {m['public']} | {m['routes']} | "
          f"{'yes' if m['q_screens'] else '—'} | {tests or '**none**'} |")
    w("")
    w("## `.q` screens (quantum_admin/components/admin)")
    w("")
    w("Each screen calls the declared services (`q:invoke service=`, `quantum_admin/services/`); "
      "**Status** is the response to a GET without a session — 302 to `/admin/login` on a protected screen.")
    w("")
    w("| Screen | Route | Auth | Status | Actions | Services | q:python (lines) | Python effects | Data source |")
    w("|---|---|---|---|---|---:|---|---|---|")
    for t in screens:
        w(f"| `{t['file'].split('components/admin/')[-1]}` | `{t['url']}` | "
          f"{'yes' if t['auth'] else '**no**'} | {t.get('status', '—')} | "
          f"{', '.join(t['actions']) or '—'} | {len(t['services'])} | {t['python']} ({t['python_lines']}) | "
          f"{', '.join(t['effects']) or '—'} | "
          f"{', '.join([f'database ({d})' for d in t['datasource']] + [f'yaml ({y})' for y in t['yaml']]) or '—'} |")
    w("")
    w("## Routes")
    w("")
    for area, rs in sorted(by_area.items()):
        w(f"### {area}")
        w("")
        w("| Verb | Path | Kind | Handler (line, lines) | Uses | UI | Status |")
        w("|---|---|---|---|---|---|---|")
        for r in sorted(rs, key=lambda r: (r["path"], r["verb"])):
            status = r.get("status", "shadowed" if r.get("shadowed_by") else "—")
            uses = ", ".join(r["uses"] + [f"*{e}*" for e in r["effects"]]) or "—"
            w(f"| {r['verb']} | `{r['path']}` | {r['kind']} | `{r['handler']}` "
              f"({r['line']}, {r['lines']}) | {uses} | {'yes' if r['called_by_ui'] else '—'} | {status} |")
        w("")
    OUTPUT.write_text("\n".join(L), encoding="utf-8")
    return len(routes), len(shadowed), ok, len(measured_gets), len(screens), len(no_auth)


def main():
    routes = routes_from_ast()
    ui = measure_app(routes)
    modules = service_modules(routes)
    screens = q_screens()
    measure_screens(screens)
    total, shadowed, ok, measured, n_screens, no_auth = write(routes, modules, screens, ui)
    print(f"{total} routes, {shadowed} shadowed, GET ok {ok}/{measured}, "
          f"{n_screens} .q screens ({no_auth} without auth) -> {OUTPUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
