"""Generate the site pages that are derived from files in the repository.

    python scripts/generate-site-pages.py          # write them
    python scripts/generate-site-pages.py --check  # exit 1 if any is stale

- docs/changelog/: one page per version from CHANGELOG.md, newest first, with
  an index. Headings carry explicit anchors ({#added}), so a link to a
  version's "Breaking" section stays valid when the text around it changes.
- docs/stability/index.md: SUPPORT_TIERS.md, the promise of 1.0.
- docs/tools/vscode-extension.md: what vscode-quantum/package.json declares.
- docs/status/index.md: FEATURE_STATUS.md ("what really works today"), which
  scripts/generate-feature-status.py measures by running the examples.
- docs/blog/index.md and docs/public/blog/feed.xml: the post list and its RSS
  feed, from the front matter of docs/blog/posts/*.md.

tests/unit/test_site_pages_are_current.py runs --check in CI, so a change to
CHANGELOG.md, FEATURE_STATUS.md or a post that is not regenerated fails there.
"""
import datetime
import html
import os
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DOCS = REPO / 'docs'

# Where the site is served. RSS needs absolute links; the pages themselves use
# relative ones, so only the feed changes when the domain does.
SITE_URL = os.environ.get('QUANTUM_SITE_URL', 'https://quantumframework.net/')

GENERATED = '<!-- Generated by scripts/generate-site-pages.py from {source}. Do not edit. -->\n'


# -- changelog ---------------------------------------------------------------

def version_slug(version: str) -> str:
    return 'v' + version.replace('.', '-')


def heading_slug(text: str) -> str:
    text = re.sub(r'`', '', text).lower()
    return re.sub(r'[^a-z0-9]+', '-', text).strip('-') or 'section'


def split_versions(text: str):
    """[(version, body)] for every `## x.y.z` section, in file order."""
    parts = re.split(r'^## (\d+\.\d+\.\d+)[^\n]*\n', text, flags=re.M)
    return [(parts[i], parts[i + 1]) for i in range(1, len(parts), 2)]


def version_page(version: str, body: str, versions):
    anchors = {v.replace('.', ''): version_slug(v) for v in versions}
    used = set()

    def heading(m):
        level, title = len(m.group(1)), m.group(2).strip()
        slug = heading_slug(title)
        base, n = slug, 2
        while slug in used:
            slug, n = f'{base}-{n}', n + 1
        used.add(slug)
        return '#' * (level - 1) + f' {title} {{#{slug}}}'

    body = re.sub(r'^(#{3,6}) (.+)$', heading, body.strip(), flags=re.M)

    # In CHANGELOG.md a version is an anchor (#0220); here it is a page.
    def link(m):
        target = m.group(1)
        if target in anchors:
            return f'](./{anchors[target]}.md)'
        return m.group(0)
    body = re.sub(r'\]\(#([0-9]+)\)', link, body)
    # A heading of this page linked from its own text keeps working.
    body = re.sub(r'\]\(#10-changes-since-0220\)', '](#1-0-changes-since-0-22-0)', body)

    i = versions.index(version)
    newer = versions[i - 1] if i > 0 else None
    older = versions[i + 1] if i + 1 < len(versions) else None
    nav = ' · '.join(filter(None, [
        f'[← {older}](./{version_slug(older)}.md)' if older else None,
        '[All versions](./index.md)',
        f'[{newer} →](./{version_slug(newer)}.md)' if newer else None,
    ]))
    return (GENERATED.format(source='CHANGELOG.md')
            + f'# Quantum {version}\n\n{body}\n\n---\n\n{nav}\n')


def changelog_pages(text: str):
    sections = split_versions(text)
    versions = [v for v, _ in sections]
    pages = {}
    for version, body in sections:
        pages[f'changelog/{version_slug(version)}.md'] = version_page(version, body, versions)
    intro = text.split('\n## ', 1)[0]
    intro = re.sub(r'^# Changelog\s*', '', intro).strip()
    lines = [GENERATED.format(source='CHANGELOG.md'), '# Changelog\n', intro + '\n',
             '| Version | Sections |', '|---|---|']
    for version, body in sections:
        heads = [h.strip() for h in re.findall(r'^#{3,4} (.+)$', body, flags=re.M)
                 if not h.startswith('1.0:')]
        kinds = ', '.join(dict.fromkeys(heads)) or '—'
        lines.append(f'| [{version}](./{version_slug(version)}.md) | {kinds} |')
    pages['changelog/index.md'] = '\n'.join(lines) + '\n'
    return pages


# -- status ------------------------------------------------------------------

def status_page(text: str) -> str:
    body = re.sub(r'^# FEATURE_STATUS[^\n]*\n', '', text)
    body = re.sub(r'^> \*\*Do not edit this file\.\*\*.*?(?=\n\n)', '', body, flags=re.S | re.M).strip()
    return (GENERATED.format(source='FEATURE_STATUS.md')
            + '# What really works today\n\n'
            'This page is measured, not written: `scripts/generate-feature-status.py` '
            'runs every example and counts what parses and what executes, and the site '
            'is regenerated from its result. Where it disagrees with the rest of the '
            'documentation, this page is the one that ran.\n\n'
            'The promise — what is Core, AI, Experimental or Laboratory — is '
            '[Support tiers](https://github.com/danielgregorio/quantum/blob/main/SUPPORT_TIERS.md).\n\n'
            + body + '\n')


# -- stability ---------------------------------------------------------------

def stability_page(text: str) -> str:
    """SUPPORT_TIERS.md as the site's Stability page: what 1.0 promises."""
    body = text.split('\n## ', 1)[1]          # from "The sentence" on; the preamble is internal history
    return (GENERATED.format(source='SUPPORT_TIERS.md')
            + '# Stability\n\n'
            'What Quantum promises, tag by tag. From 1.0, **Core and AI follow semantic '
            'versioning**: a 1.x release does not break a program that uses only them — '
            'their meaning is fixed by the rules in the [SPEC](../reference/spec.md), and a '
            'break waits for 2.0. Experimental and Laboratory carry no such promise.\n\n'
            'This page is the promise. What really runs today is measured on the '
            '[Status](../status/index.md) page, and every change is in the '
            '[Changelog](../changelog/index.md).\n\n'
            '## ' + body.rstrip() + '\n')


# -- VS Code extension -------------------------------------------------------

def vscode_page() -> str:
    """docs/tools/vscode-extension.md from vscode-quantum/package.json and its snippets.

    The hand-written page described a Marketplace listing that does not exist
    and features nobody had checked; this one lists what the extension's
    manifest declares, so it changes when the extension does.
    """
    import json
    ext = REPO / 'vscode-quantum'
    manifest = json.loads((ext / 'package.json').read_text(encoding='utf-8'))
    contributes = manifest.get('contributes', {})

    def cell(text):
        return str(text).replace('|', '\\|').replace('\n', ' ')

    lines = [GENERATED.format(source='vscode-quantum/package.json'),
             '# VS Code extension\n',
             'The extension lives in the repository, in `vscode-quantum/`. It is **not '
             'published** on the Visual Studio Marketplace; to use it, build it and run it '
             'from source (it needs Node.js):\n',
             '```bash\ncd vscode-quantum\nnpm install\nnpm run compile\n```\n',
             'Then open the `vscode-quantum` folder in VS Code and press **F5**: a second VS '
             'Code window (the Extension Development Host) opens with the extension '
             'loaded, and `.q` files get the language features below.\n',
             f'Requires VS Code {manifest.get("engines", {}).get("vscode", "")}. '
             'Features that run Quantum use the `quantum` found through the settings below.\n',
             '## Commands\n', '| Command | Title |', '|---|---|']
    for c in contributes.get('commands', []):
        lines.append(f'| `{c["command"]}` | {cell(c.get("title", ""))} |')
    keys = contributes.get('keybindings', [])
    if keys:
        lines += ['', '## Keyboard shortcuts\n', '| Keys | Command |', '|---|---|']
        for k in keys:
            lines.append(f'| `{k.get("key", "")}` | `{k.get("command", "")}` |')
    props = (contributes.get('configuration', {}) or {}).get('properties', {})
    if props:
        lines += ['', '## Settings\n', '| Setting | Default | Description |', '|---|---|---|']
        for name, spec in props.items():
            default = json.dumps(spec.get('default')) if 'default' in spec else ''
            lines.append(f'| `{name}` | `{cell(default)}` | {cell(spec.get("description", ""))} |')
    snippets = []
    for entry in contributes.get('snippets', []):
        data = json.loads((ext / entry['path']).read_text(encoding='utf-8'))
        snippets += [(s['prefix'], s.get('description', name)) for name, s in data.items()]
    if snippets:
        lines += ['', '## Snippets\n', 'Type the prefix in a `.q` file and accept the suggestion.\n',
                  '| Prefix | Inserts |', '|---|---|']
        for prefix, description in sorted(snippets):
            prefixes = prefix if isinstance(prefix, list) else [prefix]
            lines.append(f'| {", ".join(f"`{p}`" for p in prefixes)} | {cell(description)} |')
    lines += ['', 'The extension has its own completion, hover, definitions and diagnostics, '
              'built from the same tag schema as the language server. For other editors, '
              'see [LSP server](./lsp-server.md).', '']
    return '\n'.join(lines)


# -- blog --------------------------------------------------------------------

def front_matter(text: str) -> dict:
    m = re.match(r'^---\n(.*?)\n---\n', text, re.S)
    if not m:
        return {}
    data = {}
    for line in m.group(1).splitlines():
        if ':' in line:
            key, value = line.split(':', 1)
            value = value.strip()
            if value.startswith('[') and value.endswith(']'):
                value = [v.strip().strip('\'"') for v in value[1:-1].split(',') if v.strip()]
            else:
                value = value.strip('\'"')
            data[key.strip()] = value
    return data


def posts():
    out = []
    for path in sorted((DOCS / 'blog' / 'posts').glob('*.md')):
        meta = front_matter(path.read_text(encoding='utf-8'))
        for key in ('title', 'date', 'description'):
            if not meta.get(key):
                raise SystemExit(f'{path.relative_to(REPO)}: front matter needs {key}:')
        datetime.date.fromisoformat(meta['date'])
        meta['slug'] = path.stem
        meta.setdefault('tags', [])
        out.append(meta)
    return sorted(out, key=lambda p: (p['date'], p['slug']), reverse=True)


def blog_pages():
    items = posts()
    lines = [GENERATED.format(source='docs/blog/posts/'), '# Blog\n',
             'News about Quantum: releases, what changed and why. '
             'Subscribe with the [RSS feed](./feed.xml){target="_self"}.\n']
    for p in items:
        tags = ' '.join(f'`{t}`' for t in p['tags'])
        lines.append(f'## [{p["title"]}](./posts/{p["slug"]}.md)\n')
        lines.append(f'{p["date"]}{" · " + tags if tags else ""}\n')
        lines.append(f'{p["description"]}\n')
    index = '\n'.join(lines)

    now = max((p['date'] for p in items), default='1970-01-01')
    entries = []
    for p in items:
        url = f'{SITE_URL}blog/posts/{p["slug"]}'
        date = datetime.datetime.fromisoformat(p['date']).strftime('%a, %d %b %Y 00:00:00 +0000')
        entries.append(
            '    <item>\n'
            f'      <title>{html.escape(p["title"])}</title>\n'
            f'      <link>{url}</link>\n'
            f'      <guid isPermaLink="true">{url}</guid>\n'
            f'      <pubDate>{date}</pubDate>\n'
            f'      <description>{html.escape(p["description"])}</description>\n'
            + ''.join(f'      <category>{html.escape(t)}</category>\n' for t in p['tags'])
            + '    </item>\n')
    last = datetime.datetime.fromisoformat(now).strftime('%a, %d %b %Y 00:00:00 +0000')
    feed = ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<rss version="2.0">\n'
            '  <channel>\n'
            '    <title>Quantum blog</title>\n'
            f'    <link>{SITE_URL}blog/</link>\n'
            '    <description>News about Quantum: releases, what changed and why.</description>\n'
            '    <language>en</language>\n'
            f'    <lastBuildDate>{last}</lastBuildDate>\n'
            + ''.join(entries) +
            '  </channel>\n'
            '</rss>\n')
    return {'blog/index.md': index, 'public/blog/feed.xml': feed}


# -- all ---------------------------------------------------------------------

def pages() -> dict:
    out = {}
    out.update(changelog_pages((REPO / 'CHANGELOG.md').read_text(encoding='utf-8')))
    out['status/index.md'] = status_page((REPO / 'FEATURE_STATUS.md').read_text(encoding='utf-8'))
    out['stability/index.md'] = stability_page((REPO / 'SUPPORT_TIERS.md').read_text(encoding='utf-8'))
    out['tools/vscode-extension.md'] = vscode_page()
    out.update(blog_pages())
    return out


def stale(expected: dict):
    """Pages that differ from what the sources give, and generated pages that should not exist."""
    wrong = [rel for rel, text in expected.items()
             if not (DOCS / rel).is_file()
             or (DOCS / rel).read_text(encoding='utf-8').replace('\r\n', '\n') != text]
    extra = [p.relative_to(DOCS).as_posix() for p in (DOCS / 'changelog').glob('v*.md')
             if p.relative_to(DOCS).as_posix() not in expected]
    return wrong + extra


def main() -> int:
    expected = pages()
    if '--check' in sys.argv:
        bad = stale(expected)
        for rel in bad:
            print(f'docs/{rel} is stale')
        if bad:
            print('run: python scripts/generate-site-pages.py')
        return 1 if bad else 0
    for p in (DOCS / 'changelog').glob('v*.md'):
        if p.relative_to(DOCS).as_posix() not in expected:
            p.unlink()
    for rel, text in expected.items():
        target = DOCS / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding='utf-8', newline='\n')
    print(f'{len(expected)} pages written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
