"""Run the Cookbook's recipes and write what they show; build the Cookbook index.

    python scripts/generate-cookbook.py          # write
    python scripts/generate-cookbook.py --check  # exit 1 if anything shown is stale

A recipe is a folder examples/cookbook/<topic>/<name>/ — a small app
(quantum.config.yaml, components/, migrations/ when it has a database) with
its tests in tests/*.test.q. Its page, docs/cookbook/<topic>/<name>.md,
imports the files with VitePress snippets (<<< @/../examples/cookbook/…), so
the code on the page is byte for byte the code that is tested.

What a page shows as a RESULT is never typed: this script runs the recipe's
tests with `quantum test` (in this process) and writes, in the recipe's
output/ folder:

- test-report.txt — the report, with timings removed so it only changes when
  the result does;
- mail.txt — the messages `q:mail` wrote with `host: log`, if any.

tests/docs/test_cookbook.py fails when a recipe's tests fail, when an output
is stale, or when a page imports a file that does not exist.
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
RECIPES = REPO / 'examples' / 'cookbook'
PAGES = REPO / 'docs' / 'cookbook'

# Topic folder -> title, in the order the index lists them.
TOPICS = {
    'basics': 'Basics',
    'screens': 'Screens',
    'testing': 'Testing the app',
    'files-and-mail': 'Files & mail',
    'login-and-permissions': 'Login & permissions',
    'forms-and-actions': 'Forms & actions',
    'data-and-sql': 'Data & SQL',
    'ai': 'AI',
}

GENERATED = '<!-- Generated by scripts/generate-cookbook.py from docs/cookbook/*/*.md. Do not edit. -->\n'


def recipes():
    return sorted(p.parent for p in RECIPES.glob('*/*/quantum.config.yaml'))


class _MailRecorder:
    """Stands in for the mail module's logger during a run and keeps what
    `host: log` writes. Not a logging.Logger: `quantum test` silences logging
    (logging.disable), and a Logger would drop the message."""

    def __init__(self, original):
        self.original = original
        self.records = []

    def info(self, msg, *args, **kwargs):
        self.records.append(msg % args if args else msg)

    def __getattr__(self, name):
        return getattr(self.original, name)


def _graded_embed(text):
    """The stand-in's bag of words plus one dimension every text shares: unrelated
    texts score about 0.75 and related ones above 0.8 — the scale of
    nomic-embed-text, so a recipe's minRelevance means the same in CI as with a
    real model (the release run checks it: tests/live_ai/test_cookbook_ai.py)."""
    import math
    from tests.fake_ollama import embed
    vector = embed(text) + [1.0]
    norm = math.sqrt(sum(v * v for v in vector))
    return [v / norm for v in vector]


def _stand_in_reply(recipe: pathlib.Path):
    """What the stand-in model answers for an AI recipe.

    tests/fake-model.json, when the recipe has it: rules [{"when": text, "replies": [...]}];
    the first rule whose text is in the conversation answers with its reply for
    this turn (the number of assistant messages so far; the last one repeats).
    Otherwise it answers from the first numbered source, citing it — what a
    grounded answer does."""
    import json
    script = recipe / 'tests' / 'fake-model.json'
    rules = json.loads(script.read_text(encoding='utf-8')) if script.is_file() else []

    def reply(messages):
        conversation = '\n'.join(str(m.get('content', '')) for m in messages)
        turn = sum(1 for m in messages if m.get('role') == 'assistant')
        for rule in rules:
            if rule['when'].lower() in conversation.lower():
                replies = rule['replies']
                return replies[min(turn, len(replies) - 1)]
        source = re.search(r'^\[1\] \([^)]*\)\n(.*?)(?=\n\n\[2\] |\Z)', conversation, re.M | re.S)
        if not source:
            return 'I do not know.'
        text = ' '.join(line for line in source.group(1).splitlines() if not line.startswith('#'))
        sentence = re.match(r'\s*(.+?[.!?])(?:\s|$)', text, re.S)
        return f'{(sentence.group(1) if sentence else text.strip())} [1]'
    return reply


def run(recipe: pathlib.Path):
    """(passed, {output file name: text}) from running the recipe's tests.

    An AI recipe (examples/cookbook/ai/) runs against a stand-in model server
    (tests/fake_ollama.py) — never a real one, so CI needs none."""
    import contextlib
    import os
    from quantum.runtime.app_testing import run_tests

    from quantum.runtime import email_service

    lines = []
    capture = _MailRecorder(email_service.logger)
    email_service.logger = capture
    stand_in = contextlib.nullcontext()
    if recipe.parent.name == 'ai':
        from tests.fake_ollama import FakeOllama
        stand_in = FakeOllama(embed=_graded_embed)
        stand_in.reply = _stand_in_reply(recipe)
    before = os.environ.get('QUANTUM_LLM_BASE_URL')
    try:
        with stand_in as server:
            if server is not None:
                os.environ['QUANTUM_LLM_BASE_URL'] = server.url
            code = run_tests([str(recipe)], out=lambda *a: lines.append(' '.join(str(x) for x in a)))
    finally:
        email_service.logger = capture.original
        if before is None:
            os.environ.pop('QUANTUM_LLM_BASE_URL', None)
        else:
            os.environ['QUANTUM_LLM_BASE_URL'] = before

    report = '\n'.join(lines)
    report = re.sub(r'\s*\(\d+ ms\)', '', report)
    report = report.replace('\\', '/')
    report = report.replace(recipe.relative_to(REPO).as_posix() + '/', '')
    report = report.replace(str(recipe).replace('\\', '/') + '/', '')
    outputs = {'test-report.txt': report.strip() + '\n'}
    if capture.records:
        outputs['mail.txt'] = '\n\n'.join(capture.records).strip() + '\n'
    return code == 0, outputs


def front_matter(text):
    m = re.match(r'^---\n(.*?)\n---\n', text, re.S)
    data = {}
    for line in (m.group(1) if m else '').splitlines():
        if ':' in line:
            key, value = line.split(':', 1)
            data[key.strip()] = value.strip().strip('\'"')
    return data


def index_page():
    lines = [GENERATED, '# Cookbook\n',
             'Short recipes for one task each. Every recipe is a small app in '
             '`examples/cookbook/` with its own `quantum test` suite: the code on '
             'its page is imported from the tested files, and what it shows as a '
             'result was produced by running it.\n']
    for topic, title in TOPICS.items():
        # A page's `order:` (front matter) sets its place in the topic; then the file name.
        pages = [(page, front_matter(page.read_text(encoding='utf-8'))) for page in (PAGES / topic).glob('*.md')]
        pages.sort(key=lambda pm: (int(pm[1].get('order') or 99), pm[0].stem))
        if not pages:
            continue
        lines.append(f'## {title}\n')
        for page, meta in pages:
            if not meta.get('title') or not meta.get('description'):
                raise SystemExit(f'{page.relative_to(REPO)}: front matter needs title: and description:')
            lines.append(f'- [{meta["title"]}](./{topic}/{page.stem}.md) — {meta["description"]}')
        lines.append('')
    unknown = sorted({p.parent.name for p in PAGES.glob('*/*.md')} - set(TOPICS))
    if unknown:
        raise SystemExit(f'docs/cookbook/: topic folders not in TOPICS: {unknown}')
    return '\n'.join(lines)


def expected():
    """{path relative to REPO: text}, and the recipes whose tests fail."""
    out, failing = {}, []
    for recipe in recipes():
        passed, outputs = run(recipe)
        if not passed:
            failing.append(recipe.relative_to(REPO).as_posix())
        for name, text in outputs.items():
            out[(recipe / 'output' / name).relative_to(REPO).as_posix()] = text
    out['docs/cookbook/index.md'] = index_page()
    return out, failing


def stale(files):
    bad = []
    for rel, text in files.items():
        path = REPO / rel
        if not path.is_file() or path.read_text(encoding='utf-8').replace('\r\n', '\n') != text:
            bad.append(rel)
    for path in RECIPES.glob('*/*/output/*'):
        if path.relative_to(REPO).as_posix() not in files:
            bad.append(path.relative_to(REPO).as_posix())
    return bad


def main() -> int:
    sys.stdout.reconfigure(encoding='utf-8')
    files, failing = expected()
    for rel in failing:
        print(f'{rel}: its tests fail')
    if '--check' in sys.argv:
        bad = stale(files)
        for rel in bad:
            print(f'{rel} is stale')
        if bad:
            print('run: python scripts/generate-cookbook.py')
        return 1 if bad or failing else 0
    if failing:
        return 1
    for path in RECIPES.glob('*/*/output/*'):
        if path.relative_to(REPO).as_posix() not in files:
            path.unlink()
    for rel, text in files.items():
        path = REPO / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8', newline='\n')
    print(f'{len(recipes())} recipes, {len(files)} files written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
