"""Generate the site pages that are derived from files in the repository.

    python scripts/generate-site-pages.py          # write them
    python scripts/generate-site-pages.py --check  # exit 1 if any is stale

- docs/changelog/: one page per version from CHANGELOG.md, newest first, with
  an index. Headings carry explicit anchors ({#added}), so a link to a
  version's "Breaking" section stays valid when the text around it changes.
- docs/stability/index.md: SUPPORT_TIERS.md, the promise of 1.0.
- docs/tools/vscode-extension.md: what vscode-quantum/package.json declares.
- docs/status/index.md: FEATURE_STATUS.md ("what really works today"), which
  scripts/generate-feature-status.py measures by running the examples.
- docs/blog/index.md and docs/public/blog/feed.xml: the post list and its RSS
  feed, from the front matter of docs/blog/posts/*.md.

tests/unit/test_site_pages_are_current.py runs --check in CI, so a change to
CHANGELOG.md, FEATURE_STATUS.md or a post that is not regenerated fails there.
"""
import datetime
import html
import os
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DOCS = REPO / 'docs'

# Where the site is served. RSS needs absolute links; the pages themselves use
# relative ones, so only the feed changes when the domain does.
SITE_URL = os.environ.get('QUANTUM_SITE_URL', 'https://quantumframework.net/')

GENERATED = '<!-- Generated by scripts/generate-site-pages.py from {source}. Do not edit. -->\n'


# -- changelog ---------------------------------------------------------------

def version_slug(version: str) -> str:
    return 'v' + version.replace('.', '-')


def heading_slug(text: str) -> str:
    text = re.sub(r'`', '', text).lower()
    return re.sub(r'[^a-z0-9]+', '-', text).strip('-') or 'section'


def split_versions(text: str):
    """[(version, body)] for every `## x.y.z` section, in file order."""
    parts = re.split(r'^## (\d+\.\d+\.\d+)[^\n]*\n', text, flags=re.M)
    return [(parts[i], parts[i + 1]) for i in range(1, len(parts), 2)]


def version_page(version: str, body: str, versions):
    anchors = {v.replace('.', ''): version_slug(v) for v in versions}
    used = set()

    def heading(m):
        level, title = len(m.group(1)), m.group(2).strip()
        slug = heading_slug(title)
        base, n = slug, 2
        while slug in used:
            slug, n = f'{base}-{n}', n + 1
        used.add(slug)
        return '#' * (level - 1) + f' {title} {{#{slug}}}'

    body = re.sub(r'^(#{3,6}) (.+)$', heading, body.strip(), flags=re.M)

    # In CHANGELOG.md a version is an anchor (#0220); here it is a page.
    def link(m):
        target = m.group(1)
        if target in anchors:
            return f'](./{anchors[target]}.md)'
        return m.group(0)
    body = re.sub(r'\]\(#([0-9]+)\)', link, body)
    # A heading of this page linked from its own text keeps working.
    body = re.sub(r'\]\(#10-changes-since-0220\)', '](#1-0-changes-since-0-22-0)', body)

    i = versions.index(version)
    newer = versions[i - 1] if i > 0 else None
    older = versions[i + 1] if i + 1 < len(versions) else None
    nav = ' · '.join(filter(None, [
        f'[← {older}](./{version_slug(older)}.md)' if older else None,
        '[All versions](./index.md)',
        f'[{newer} →](./{version_slug(newer)}.md)' if newer else None,
    ]))
    return (GENERATED.format(source='CHANGELOG.md')
            + f'# Quantum {version}\n\n{body}\n\n---\n\n{nav}\n')


def changelog_pages(text: str):
    sections = split_versions(text)
    versions = [v for v, _ in sections]
    pages = {}
    for version, body in sections:
        pages[f'changelog/{version_slug(version)}.md'] = version_page(version, body, versions)
    intro = text.split('\n## ', 1)[0]
    intro = re.sub(r'^# Changelog\s*', '', intro).strip()
    lines = [GENERATED.format(source='CHANGELOG.md'), '# Changelog\n', intro + '\n',
             '| Version | Sections |', '|---|---|']
    for version, body in sections:
        heads = [h.strip() for h in re.findall(r'^#{3,4} (.+)$', body, flags=re.M)
                 if not h.startswith('1.0:')]
        kinds = ', '.join(dict.fromkeys(heads)) or '—'
        lines.append(f'| [{version}](./{version_slug(version)}.md) | {kinds} |')
    pages['changelog/index.md'] = '\n'.join(lines) + '\n'
    return pages


# -- status ------------------------------------------------------------------

def status_page(text: str) -> str:
    body = re.sub(r'^# FEATURE_STATUS[^\n]*\n', '', text)
    body = re.sub(r'^> \*\*Do not edit this file\.\*\*.*?(?=\n\n)', '', body, flags=re.S | re.M).strip()
    return (GENERATED.format(source='FEATURE_STATUS.md')
            + '# What really works today\n\n'
            'This page is measured, not written: `scripts/generate-feature-status.py` '
            'runs every example and counts what parses and what executes, and the site '
            'is regenerated from its result. Where it disagrees with the rest of the '
            'documentation, this page is the one that ran.\n\n'
            'The promise — what is Core, AI, Experimental or Laboratory — is '
            '[Support tiers](https://github.com/danielgregorio/quantum/blob/main/SUPPORT_TIERS.md).\n\n'
            + body + '\n')


# -- stability ---------------------------------------------------------------

def stability_page(text: str) -> str:
    """SUPPORT_TIERS.md as the site's Stability page: what 1.0 promises."""
    body = text.split('\n## ', 1)[1]          # from "The sentence" on; the preamble is internal history
    return (GENERATED.format(source='SUPPORT_TIERS.md')
            + '# Stability\n\n'
            'What Quantum promises, tag by tag. From 1.0, **Core and AI follow semantic '
            'versioning**: a 1.x release does not break a program that uses only them — '
            'their meaning is fixed by the rules in the [SPEC](../reference/spec.md), and a '
            'break waits for 2.0. Experimental and Laboratory carry no such promise.\n\n'
            'This page is the promise. What really runs today is measured on the '
            '[Status](../status/index.md) page, and every change is in the '
            '[Changelog](../changelog/index.md).\n\n'
            '## ' + body.rstrip() + '\n')


# -- VS Code extension -------------------------------------------------------

# The VS Code page's own words, per language. The tables are the manifest's: the
# command titles, setting descriptions and snippet names are the extension's own
# (English) interface, the same in every language.
VSCODE_TEXT = {
    'en': {
        'title': 'VS Code extension',
        'intro': ('The extension lives in the repository, in `vscode-quantum/`. It is **not '
                  'published** on the Visual Studio Marketplace; to use it, build it and run it '
                  'from source (it needs Node.js):'),
        'f5': ('Then open the `vscode-quantum` folder in VS Code and press **F5**: a second VS '
               'Code window (the Extension Development Host) opens with the extension '
               'loaded, and `.q` files get the language features below.'),
        'requires': ('Requires VS Code {engine}. Features that run Quantum use the `quantum` found '
                     'through the settings below.'),
        'commands': 'Commands', 'command': 'Command', 'cmd_title': 'Title',
        'keys_title': 'Keyboard shortcuts', 'keys': 'Keys',
        'settings': 'Settings', 'setting': 'Setting', 'default': 'Default', 'description': 'Description',
        'snippets': 'Snippets', 'snippets_intro': 'Type the prefix in a `.q` file and accept the suggestion.',
        'prefix': 'Prefix', 'inserts': 'Inserts',
        'outro': ('The extension has its own completion, hover, definitions and diagnostics, '
                  'built from the same tag schema as the language server. For other editors, '
                  'see [LSP server](./lsp-server.md).'),
    },
    'pt': {
        'title': 'Extensão do VS Code',
        'notice': ('::: info Tradução automática\nEsta página foi traduzida automaticamente do '
                   'inglês e ainda não foi revisada\npor um falante nativo; correções são '
                   'bem-vindas no GitHub. Se algo não bater,\nvale o '
                   '[original em inglês](/tools/vscode-extension).\n:::\n'),
        'intro': ('A extensão fica no repositório, em `vscode-quantum/`. Ela **não está publicada** '
                  'no Visual Studio Marketplace; para usá-la, compile e rode a partir do código-fonte '
                  '(precisa de Node.js):'),
        'f5': ('Depois abra a pasta `vscode-quantum` no VS Code e aperte **F5**: uma segunda janela '
               'do VS Code (o Extension Development Host) abre com a extensão carregada, e os '
               'arquivos `.q` ganham os recursos abaixo.'),
        'requires': ('Requer VS Code {engine}. Os recursos que executam o Quantum usam o `quantum` '
                     'encontrado pelas configurações abaixo.'),
        'commands': 'Comandos', 'command': 'Comando', 'cmd_title': 'Título',
        'keys_title': 'Atalhos de teclado', 'keys': 'Teclas',
        'settings': 'Configurações', 'setting': 'Configuração', 'default': 'Padrão',
        'description': 'Descrição',
        'snippets': 'Snippets', 'snippets_intro': 'Digite o prefixo num arquivo `.q` e aceite a sugestão.',
        'prefix': 'Prefixo', 'inserts': 'Insere',
        'outro': ('A extensão tem o seu próprio autocompletar, hover, definições e diagnósticos, '
                  'construídos a partir do mesmo esquema de tags do servidor de linguagem. Para '
                  'outros editores, veja o [servidor LSP](./lsp-server.md).'),
    },
    'es': {
        'title': 'Extensión de VS Code',
        'notice': ('::: info Traducción automática\nEsta página se tradujo automáticamente del inglés y '
                   'todavía no la revisó un\nhablante nativo; las correcciones son bienvenidas en GitHub. '
                   'Si algo no\ncoincide, vale el [original en inglés](/tools/vscode-extension).\n:::\n'),
        'intro': ('La extensión vive en el repositorio, en `vscode-quantum/`. **No está publicada** en '
                  'el Visual Studio Marketplace; para usarla, compílala y ejecútala desde el código '
                  'fuente (necesita Node.js):'),
        'f5': ('Luego abre la carpeta `vscode-quantum` en VS Code y presiona **F5**: se abre una '
               'segunda ventana de VS Code (el Extension Development Host) con la extensión cargada, '
               'y los archivos `.q` obtienen las funciones de abajo.'),
        'requires': ('Requiere VS Code {engine}. Las funciones que ejecutan Quantum usan el `quantum` '
                     'que encuentran las configuraciones de abajo.'),
        'commands': 'Comandos', 'command': 'Comando', 'cmd_title': 'Título',
        'keys_title': 'Atajos de teclado', 'keys': 'Teclas',
        'settings': 'Configuración', 'setting': 'Ajuste', 'default': 'Valor por defecto',
        'description': 'Descripción',
        'snippets': 'Snippets',
        'snippets_intro': 'Escribe el prefijo en un archivo `.q` y acepta la sugerencia.',
        'prefix': 'Prefijo', 'inserts': 'Inserta',
        'outro': ('La extensión tiene su propio autocompletado, hover, definiciones y diagnósticos, '
                  'construidos a partir del mismo esquema de etiquetas que el servidor de lenguaje. '
                  'Para otros editores, consulta el [servidor LSP](./lsp-server.md).'),
    },
    'zh': {
        'title': 'VS Code 扩展',
        'notice': ('::: info 机器翻译\n本页由英文原文机器翻译而来，尚未经过母语审校，欢迎在 GitHub 上提出修改。'
                   '内容如有出入，以[英文原文](/tools/vscode-extension)为准。\n:::\n'),
        'intro': ('扩展位于仓库的 `vscode-quantum/` 中。它**没有发布**到 Visual Studio Marketplace；'
                  '要使用它，需要从源码构建并运行（需要 Node.js）：'),
        'f5': ('然后在 VS Code 中打开 `vscode-quantum` 文件夹并按 **F5**：会打开第二个 VS Code 窗口'
               '（Extension Development Host），其中加载了该扩展，`.q` 文件即可获得下面的语言功能。'),
        'requires': '需要 VS Code {engine}。运行 Quantum 的功能使用下面设置中找到的 `quantum`。',
        'commands': '命令', 'command': '命令', 'cmd_title': '标题',
        'keys_title': '快捷键', 'keys': '按键',
        'settings': '设置', 'setting': '设置项', 'default': '默认值', 'description': '说明',
        'snippets': '代码片段', 'snippets_intro': '在 `.q` 文件中输入前缀并接受建议。',
        'prefix': '前缀', 'inserts': '插入',
        'outro': ('扩展有自己的补全、悬停提示、定义跳转和诊断，基于与语言服务器相同的标签结构构建。'
                  '其他编辑器请参见 [LSP 服务器](./lsp-server.md)。'),
    },
}


def vscode_page(lang: str = 'en') -> str:
    """docs/tools/vscode-extension.md from vscode-quantum/package.json and its snippets
    — or its translation, docs/<lang>/tools/vscode-extension.md, stamped with the
    English page's hash (the tables stay the manifest's own English strings).

    The hand-written page described a Marketplace listing that does not exist
    and features nobody had checked; this one lists what the extension's
    manifest declares, so it changes when the extension does.
    """
    import json
    w = VSCODE_TEXT[lang]
    ext = REPO / 'vscode-quantum'
    manifest = json.loads((ext / 'package.json').read_text(encoding='utf-8'))
    contributes = manifest.get('contributes', {})

    def cell(text):
        return str(text).replace('|', '\\|').replace('\n', ' ')

    lines = [] if lang == 'en' else [_stamped('tools/vscode-extension.md', vscode_page())]
    lines += [GENERATED.format(source='vscode-quantum/package.json'), f'# {w["title"]}\n']
    if lang != 'en':
        lines.append(w['notice'])
    lines += [w['intro'] + '\n',
              '```bash\ncd vscode-quantum\nnpm install\nnpm run compile\n```\n',
              w['f5'] + '\n',
              w['requires'].format(engine=manifest.get('engines', {}).get('vscode', '')) + '\n',
              f'## {w["commands"]}\n', f'| {w["command"]} | {w["cmd_title"]} |', '|---|---|']
    for c in contributes.get('commands', []):
        lines.append(f'| `{c["command"]}` | {cell(c.get("title", ""))} |')
    keys = contributes.get('keybindings', [])
    if keys:
        lines += ['', f'## {w["keys_title"]}\n', f'| {w["keys"]} | {w["command"]} |', '|---|---|']
        for k in keys:
            lines.append(f'| `{k.get("key", "")}` | `{k.get("command", "")}` |')
    props = (contributes.get('configuration', {}) or {}).get('properties', {})
    if props:
        lines += ['', f'## {w["settings"]}\n',
                  f'| {w["setting"]} | {w["default"]} | {w["description"]} |', '|---|---|---|']
        for name, spec in props.items():
            default = json.dumps(spec.get('default')) if 'default' in spec else ''
            lines.append(f'| `{name}` | `{cell(default)}` | {cell(spec.get("description", ""))} |')
    snippets = []
    for entry in contributes.get('snippets', []):
        data = json.loads((ext / entry['path']).read_text(encoding='utf-8'))
        snippets += [(s['prefix'], s.get('description', name)) for name, s in data.items()]
    if snippets:
        lines += ['', f'## {w["snippets"]}\n', w['snippets_intro'] + '\n',
                  f'| {w["prefix"]} | {w["inserts"]} |', '|---|---|']
        for prefix, description in sorted(snippets):
            prefixes = prefix if isinstance(prefix, list) else [prefix]
            lines.append(f'| {", ".join(f"`{p}`" for p in prefixes)} | {cell(description)} |')
    lines += ['', w['outro'], '']
    return '\n'.join(lines)


# -- blog --------------------------------------------------------------------

def front_matter(text: str) -> dict:
    m = re.match(r'^---\n(.*?)\n---\n', text, re.S)
    if not m:
        return {}
    data = {}
    for line in m.group(1).splitlines():
        if ':' in line:
            key, value = line.split(':', 1)
            value = value.strip()
            if value.startswith('[') and value.endswith(']'):
                value = [v.strip().strip('\'"') for v in value[1:-1].split(',') if v.strip()]
            else:
                value = value.strip('\'"')
            data[key.strip()] = value
    return data


def posts():
    out = []
    for path in sorted((DOCS / 'blog' / 'posts').glob('*.md')):
        meta = front_matter(path.read_text(encoding='utf-8'))
        for key in ('title', 'date', 'description'):
            if not meta.get(key):
                raise SystemExit(f'{path.relative_to(REPO)}: front matter needs {key}:')
        datetime.date.fromisoformat(meta['date'])
        meta['slug'] = path.stem
        meta.setdefault('tags', [])
        out.append(meta)
    return sorted(out, key=lambda p: (p['date'], p['slug']), reverse=True)


def blog_pages():
    items = posts()
    lines = [GENERATED.format(source='docs/blog/posts/'), '# Blog\n',
             'News about Quantum: releases, what changed and why. '
             'Subscribe with the [RSS feed](./feed.xml){target="_self"}.\n']
    for p in items:
        tags = ' '.join(f'`{t}`' for t in p['tags'])
        lines.append(f'## [{p["title"]}](./posts/{p["slug"]}.md)\n')
        lines.append(f'{p["date"]}{" · " + tags if tags else ""}\n')
        lines.append(f'{p["description"]}\n')
    index = '\n'.join(lines)

    now = max((p['date'] for p in items), default='1970-01-01')
    entries = []
    for p in items:
        url = f'{SITE_URL}blog/posts/{p["slug"]}'
        date = datetime.datetime.fromisoformat(p['date']).strftime('%a, %d %b %Y 00:00:00 +0000')
        entries.append(
            '    <item>\n'
            f'      <title>{html.escape(p["title"])}</title>\n'
            f'      <link>{url}</link>\n'
            f'      <guid isPermaLink="true">{url}</guid>\n'
            f'      <pubDate>{date}</pubDate>\n'
            f'      <description>{html.escape(p["description"])}</description>\n'
            + ''.join(f'      <category>{html.escape(t)}</category>\n' for t in p['tags'])
            + '    </item>\n')
    last = datetime.datetime.fromisoformat(now).strftime('%a, %d %b %Y 00:00:00 +0000')
    feed = ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<rss version="2.0">\n'
            '  <channel>\n'
            '    <title>Quantum blog</title>\n'
            f'    <link>{SITE_URL}blog/</link>\n'
            '    <description>News about Quantum: releases, what changed and why.</description>\n'
            '    <language>en</language>\n'
            f'    <lastBuildDate>{last}</lastBuildDate>\n'
            + ''.join(entries) +
            '  </channel>\n'
            '</rss>\n')
    return {'blog/index.md': index, 'public/blog/feed.xml': feed}


# -- translations ------------------------------------------------------------

# The generated pages of a language (docs/<lang>/status/, docs/<lang>/blog/):
# the language's own words around the same measured tables and the same posts.
# Each is stamped with the hash of the English page it was generated beside,
# as scripts/translation-status.py stamps a hand-translated page.
LANGS = {
    'pt': {
        'notice': ('::: info Tradução automática\nEsta página foi traduzida automaticamente do '
                   'inglês e ainda não foi revisada\npor um falante nativo; correções são '
                   'bem-vindas no GitHub. Se algo não bater,\nvale o [original em inglês]({url}).\n:::\n'),
        'status_title': 'O que funciona de verdade hoje',
        'status_intro': ('Esta página é medida, não escrita: o `scripts/generate-feature-status.py` '
                         'roda cada exemplo e conta o que passa pelo parser e o que executa, e o '
                         'site é gerado de novo a partir do resultado. Onde ela discorda do resto '
                         'da documentação, esta é a página que rodou. As tabelas ficam em inglês, '
                         'como o script as escreve.\n\n'
                         'A promessa — o que é Núcleo (Core), IA, Experimental ou Laboratório — '
                         'está em [Estabilidade](/pt/stability/).'),
        'blog_intro': ('Notícias do Quantum: versões, o que mudou e por quê. Assine com o '
                       '[feed RSS](/blog/feed.xml){target="_self"} (em inglês).'),
        'english': ' (em inglês)',
    },
    'es': {
        'notice': ('::: info Traducción automática\nEsta página se tradujo automáticamente del '
                   'inglés y todavía no la revisó un\nhablante nativo; las correcciones son '
                   'bienvenidas en GitHub. Si algo no\ncoincide, vale el [original en inglés]({url}).\n:::\n'),
        'status_title': 'Lo que de verdad funciona hoy',
        'status_intro': ('Esta página se mide, no se escribe: `scripts/generate-feature-status.py` '
                         'ejecuta cada ejemplo y cuenta lo que pasa el analizador y lo que se '
                         'ejecuta, y el sitio se vuelve a generar a partir del resultado. Donde '
                         'no coincida con el resto de la documentación, esta es la página que se '
                         'ejecutó. Las tablas quedan en inglés, como las escribe el script.\n\n'
                         'La promesa — qué es Núcleo (Core), IA, Experimental o Laboratorio — '
                         'está en [Estabilidad](/es/stability/).'),
        'blog_intro': ('Noticias de Quantum: versiones, qué cambió y por qué. Suscríbete con el '
                       '[feed RSS](/blog/feed.xml){target="_self"} (en inglés).'),
        'english': ' (en inglés)',
    },
    'zh': {
        'notice': ('::: info 机器翻译\n本页由英文原文机器翻译而来，尚未经过母语审校，欢迎在 GitHub 上提出修改。'
                   '内容如有出入，以[英文原文]({url})为准。\n:::\n'),
        'status_title': '今天真正能用的功能',
        'status_intro': ('本页是测量出来的，不是写出来的：`scripts/generate-feature-status.py` '
                         '运行每个示例，统计哪些能通过解析、哪些能执行，网站再根据结果重新生成。'
                         '如果它与文档的其他部分不一致，以这一页为准——它是实际运行的结果。'
                         '表格保持英文，与脚本输出一致。\n\n'
                         '承诺——哪些属于核心层（Core）、AI 层、实验层或实验室——见'
                         '[稳定性](/zh/stability/)。'),
        'blog_intro': ('Quantum 的新闻：版本发布、改了什么以及为什么。可通过 '
                       '[RSS 订阅](/blog/feed.xml){target="_self"}（英文）。'),
        'english': '（英文）',
    },
}


def _source_hash(text: str) -> str:
    """As scripts/translation-status.py (and the site) hash a translation's source."""
    import hashlib
    return hashlib.sha256(text.replace('\r\n', '\n').encode('utf-8')).hexdigest()[:12]


def _stamped(source: str, english: str) -> str:
    return f'---\nsource: {source}\nsource_hash: {_source_hash(english)}\n---\n'


def translated_pages(english: dict) -> dict:
    out = {}
    for lang, words in LANGS.items():
        status = english['status/index.md']
        body = status.split('\n\n', 3)[3]         # the measured part, after title, intro and tiers line
        out[f'{lang}/status/index.md'] = (
            _stamped('status/index.md', status) + GENERATED.format(source='FEATURE_STATUS.md')
            + f'# {words["status_title"]}\n\n' + words['notice'].format(url='/status/') + '\n'
            + words['status_intro'] + '\n\n' + body)

        lines = [_stamped('blog/index.md', english['blog/index.md'])
                 + GENERATED.format(source=f'docs/blog/posts/ and docs/{lang}/blog/posts/'), '# Blog\n',
                 words['notice'].format(url='/blog/'), words['blog_intro'] + '\n']
        for p in posts():
            mine = DOCS / lang / 'blog' / 'posts' / f'{p["slug"]}.md'
            tags = ' '.join(f'`{t}`' for t in p['tags'])
            if mine.is_file():
                meta = {**p, **front_matter(mine.read_text(encoding='utf-8'))}
                lines.append(f'## [{meta["title"]}](./posts/{p["slug"]}.md)\n')
            else:
                meta = p
                lines.append(f'## [{p["title"]}](/blog/posts/{p["slug"]}){words["english"]}\n')
            lines.append(f'{p["date"]}{" · " + tags if tags else ""}\n')
            lines.append(f'{meta["description"]}\n')
        out[f'{lang}/blog/index.md'] = '\n'.join(lines)
    return out


# -- all ---------------------------------------------------------------------

def pages() -> dict:
    out = {}
    out.update(changelog_pages((REPO / 'CHANGELOG.md').read_text(encoding='utf-8')))
    out['status/index.md'] = status_page((REPO / 'FEATURE_STATUS.md').read_text(encoding='utf-8'))
    out['stability/index.md'] = stability_page((REPO / 'SUPPORT_TIERS.md').read_text(encoding='utf-8'))
    out['tools/vscode-extension.md'] = vscode_page()
    for lang in ('pt', 'es', 'zh'):
        out[f'{lang}/tools/vscode-extension.md'] = vscode_page(lang)
    out.update(blog_pages())
    out.update(translated_pages(out))
    return out


def stale(expected: dict):
    """Pages that differ from what the sources give, and generated pages that should not exist."""
    wrong = [rel for rel, text in expected.items()
             if not (DOCS / rel).is_file()
             or (DOCS / rel).read_text(encoding='utf-8').replace('\r\n', '\n') != text]
    extra = [p.relative_to(DOCS).as_posix() for p in (DOCS / 'changelog').glob('v*.md')
             if p.relative_to(DOCS).as_posix() not in expected]
    return wrong + extra


def main() -> int:
    expected = pages()
    if '--check' in sys.argv:
        bad = stale(expected)
        for rel in bad:
            print(f'docs/{rel} is stale')
        if bad:
            print('run: python scripts/generate-site-pages.py')
        return 1 if bad else 0
    for p in (DOCS / 'changelog').glob('v*.md'):
        if p.relative_to(DOCS).as_posix() not in expected:
            p.unlink()
    for rel, text in expected.items():
        target = DOCS / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding='utf-8', newline='\n')
    print(f'{len(expected)} pages written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
