#!/usr/bin/env python
"""Generate docs/targets/games.md — the game language — from the schema. Never by hand.

    python scripts/generate-games-reference.py          # rewrite the page
    python scripts/generate-games-reference.py --check  # exit 1 when the page is stale

The tags, their attributes and what they mean come from
quantum/runtime/godot/schema.py: the table the compiler validates against,
so the page cannot say what the compiler does not. The games are
included whole: they are the examples, and they are replayed in CI.

tests/docs/test_games_reference_is_generated.py fails when the committed
page is not this script's output.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from quantum.runtime.godot import gd  # noqa: E402
from quantum.runtime.godot.schema import ACTIONS, STATEMENTS, TAGS  # noqa: E402
from quantum.runtime.godot_bin import GODOT_VERSION  # noqa: E402

OUT = REPO / 'docs' / 'targets' / 'games.md'
GAMES = [
    ('Hopper', 'projects/hopper/hopper.q', 'a platformer: a world map, three levels (one drawn in Tiled), '
     'a block with a power-up, walkers to stomp, a pit, a checkpoint, spikes, a flag, a game over'),
    ('Keep', 'projects/keep/keep.q', 'a top-down adventure: six rooms, slimes that wander and bats that '
     'chase, a sword, a key and a locked door, a switch that opens a gate in another room, a chest'),
    ('Drift', 'projects/drift/drift.q', 'a vertical shooter: three waves from the scene\'s seed, '
     'drones and tanks that shoot, a boss with two phases, a high score kept between runs'),
    ('Pong', 'projects/pong/pong.q', 'Godot\'s own Pong demo transcribed tag for node: two players, '
     'a ball that flies and bounces, zones at the edges (projects/pong/README.md maps the original to it)'),
    ('Creeps', 'projects/creeps/creeps.q', 'Godot\'s "Dodge the Creeps" tutorial game transcribed: a title, '
     'creeps from the border at random speeds, a score a second, a game over (projects/creeps/README.md)'),
    ('Towers', 'projects/towers/towers.q', 'a tower defense transcribed from an MIT Godot template: a cursor, '
     'turrets that shoot the nearest dino, dinos down a path in waves, gold and a base; two players over the '
     'network (projects/towers/README.md)'),
]

INTRO = f'''---
title: Games (Laboratory)
outline: [2, 3]
---

<!-- Generated by scripts/generate-games-reference.py from quantum/runtime/godot/schema.py. Do not edit. -->

# Games

> **Laboratory.** The game engine exists to press on the language; it carries
> no stability promise and may change in any release (`SUPPORT_TIERS.md`).

A `q:application type="game"` is a game: scenes, prefabs, a character, and
what happens when things touch — in tags. It compiles to a
[Godot {GODOT_VERSION}](https://godotengine.org) project: `game.json` holds
everything declarative, one GDScript per scene holds the logic you wrote
(`q:set`, `q:if`, `q:loop`, `q:function` and the action tags, compiled), and
`addons/quantum/` is the runtime, the same in every game. There is no script
of your own anywhere: text where statements go is a compile error.

```bash
quantum run game.q            # writes projects/<id>/godot/, which Godot opens, runs and exports
quantum run game.q --check    # ...and opens it headless: any script error fails the build
python scripts/godot.py install   # the pinned Godot, into ~/.cache/quantum/godot
```

The same inputs give the same game: all logic runs on the fixed physics
tick, the only random source is seeded per scene, and
`quantum.runtime.godot_replay.replay()` runs a build for N ticks under an
input tape and returns its state — which is how the games below are tested
in CI (`tests/godot/`).

```python
from quantum.runtime.godot_replay import replay, tape_from_holds

state = replay('projects/hopper/godot', ticks=120,
               tape=tape_from_holds([('right', 0, 120), ('jump', 52, 72)]))
state['level-1']['game']['score']     # 110: a coin and a stomp
```

## The shape of a game

```xml
<q:application id="hopper" type="game">
  <q:set name="lives" value="3" type="number" />          <!-- game state: kept across scenes -->
  <q:set name="best" value="0" type="number" saved="true" /> <!-- ...and between runs -->

  <qg:tileset name="kenney" src="assets/kenney/tilemap_packed.png" tile="18" />
  <qg:spritesheet name="chars" src="assets/kenney/tilemap-characters_packed.png" tile="24" />
  <qg:sound name="coin" src="assets/kenney/audio/coin.ogg" />

  <qg:prefab name="Coin" tag="coin" sheet="kenney" frame="151" hitbox="12x12" />
  <qg:prefab name="Walker" tag="enemy" sheet="chars" frame="18" hitbox="18x18" ai="patrol" speed="30" />

  <qg:scene name="level-1" width="256" height="224" seed="7">
    <q:set name="coins" value="0" type="number" />        <!-- scene state: reset on entry -->
    <qg:tilemap tileset="kenney" collision="true">
0,0,0,0
23,23,23,23
    </qg:tilemap>
    <qg:character id="player" controller="platformer" sheet="chars" x="40" y="160" hitbox="18x22">
      <qg:on-collision with="coin">
        <qg:destroy target="other" /> <qg:play sound="coin" />
        <q:set name="coins" value="{{coins + 1}}" />
      </qg:on-collision>
      <qg:on-collision with="enemy" side="top"> <qg:destroy /> <qg:bounce /> </qg:on-collision>
    </qg:character>
    <qg:instance prefab="Coin" x="120" y="160" />
    <qg:camera follow="player" />
    <qg:hud><qg:counter bind="coins" label="COINS" /></qg:hud>
  </qg:scene>
</q:application>
```

Expressions are the language's (`{{coins + 1}}`, `{{me.state == 'big'}}`,
`{{'key-1' not in taken}}`), compiled to GDScript with the same meaning:
`/` is a float division, `%` follows the divisor's sign, `len` works on a
string, an array or a dictionary. Every name must be declared (a `q:set` of
the scene or the game, a parameter, a loop variable, or `me`/`other` in a
handler): a typo is a compile error, not a null in Godot.

In a handler, `me` is the character or prefab the handler belongs to and
`other` what it touched; `me.state`, `me.health`, `other.name` read them.
'''


def _type(t: str) -> str:
    if t.startswith('enum:'):
        return ' / '.join(f'`{o}`' for o in t[5:].split('|'))
    return {'str': 'text', 'int': 'integer', 'float': 'number', 'bool': 'true / false',
            'ident': 'a name', 'size': '`WxH` pixels', 'color': '`#rrggbb`', 'expr': 'an expression'}.get(t, t)


def _default(attr) -> str:
    if attr.required:
        return 'required'
    if attr.default is None:
        return ''
    if isinstance(attr.default, bool):
        return '`true`' if attr.default else '`false`'
    return f'`{attr.default}`'


def tag_section(name: str, depth: str = '###') -> str:
    tag = TAGS[name]
    lines = [f'{depth} `qg:{name}`', '', tag.doc, '']
    if tag.attrs:
        lines += ['| Attribute | Type | Default | Meaning |', '|---|---|---|---|']
        for aname, attr in tag.attrs.items():
            lines.append(f'| `{aname}` | {_type(attr.type)} | {_default(attr)} | {attr.doc} |')
        lines.append('')
    if tag.text:
        lines += [f'Holds {tag.text}.', '']
    where = ', '.join({'application': '`q:application`', 'handler': 'a handler'}.get(p, f'`qg:{p}`')
                      for p in tag.parents)
    lines += [f'Goes inside: {where}.', '']
    return '\n'.join(lines)


GD_EXAMPLE = '''<q:application id="smooth" type="game">
  <qg:tileset name="k" src="assets/kenney/tilemap_packed.png" tile="18" />
  <qg:spritesheet name="c" src="assets/kenney/tilemap-characters_packed.png" tile="24" />
  <qg:prefab name="Coin" tag="coin" sheet="k" frame="151" hitbox="12x12" gd:modulate="#ffd700" />
  <qg:scene name="main">
    <qg:tilemap tileset="k" collision="true">
0,0,0,0,0
23,23,23,23,23
    </qg:tilemap>
    <qg:character id="player" controller="platformer" sheet="c" x="20" y="10" hitbox="18x22" />
    <qg:instance prefab="Coin" x="60" y="10" gd:scale="1.5,1.5" />
    <qg:camera follow="player" gd:zoom="2,2" gd:position_smoothing_enabled="true" gd:position_smoothing_speed="8" />
  </qg:scene>
</q:application>'''


def gd_section() -> str:
    table = gd.table()
    classes = {}
    for tag, cls in sorted(gd.NODE_CLASS.items()):
        classes.setdefault(cls, []).append(f'`qg:{tag}`')
    for kind, cls in gd.PREFAB_CLASS.items():
        classes.setdefault(cls, []).append(f'{"an" if kind == "item" else "a"} {kind} prefab and its instances')
    rows = '\n'.join(f'| {cls} | {", ".join(tags)} | {len(gd.properties_of(cls))} |' for cls, tags in classes.items())
    return (f'''## `gd:` attributes

Every tag above becomes a Godot node, and `gd:name="value"` sets a property of that
node, as it is: the compiler forwards it, the runtime calls `node.set()` once as the
scene is built, and nothing is reimplemented. The name must be a property of the
node's class (inherited ones included), with a type the compiler can write: `float`,
`int`, `bool`, `String`, `Vector2` and `Vector2i` as `x,y`, `Color` as `#rrggbb` or
`#rrggbbaa`. Anything else — a property the class does not have, a value of the wrong
type, a `gd:` on a tag that becomes no node (`qg:tileset`, `qg:spritesheet`) — is a
compile error with the line, and the error names the properties the class does have.

The table is Godot {table['godot']}'s own class reference
(`quantum/runtime/godot/godot_properties.json`, generated by
`scripts/generate-godot-properties.py`). Properties only: methods, signals, and what
the runtime sets from the language's attributes (`position`, `velocity`, `name`, the
collision layers) are not forwarded. When the same `gd:` attribute shows up in a
second game, it is a `qg:` attribute waiting to be named.

| Node | Tags | Properties |
|---|---|---|
{rows}

```xml
{GD_EXAMPLE}
```
''')


def build() -> str:
    parts = [INTRO]
    groups = [
        ('What a game is made of', 'Declared once, in `q:application`.',
         ['tileset', 'spritesheet', 'input', 'multiplayer', 'sound', 'prefab', 'animation', 'state', 'scene']),
        ('What a scene holds', 'The level, the character, the things placed in it, and what the screen shows.',
         ['tilemap', 'character', 'instance', 'spawner', 'zone', 'sprite', 'path', 'cursor', 'exit', 'map-node',
          'map-path', 'camera', 'hud', 'counter', 'text']),
        ('Handlers', 'Where the logic goes: actions and statements, with `me` and `other` '
         '(`cursor` and `other` in qg:on-select).',
         ['on-collision', 'on-hit', 'on-fall', 'on-input', 'on-select', 'on-damage', 'on-death']),
        ('Actions', 'What a handler can do, besides `q:set`, `q:if`, `q:loop`, `q:call` and `q:return`.',
         list(ACTIONS)),
    ]
    covered = set()
    for title, blurb, names in groups:
        parts.append(f'## {title}\n\n{blurb}\n')
        for n in names:
            parts.append(tag_section(n))
            covered.add(n)
    missing = sorted(set(TAGS) - covered)
    if missing:
        parts.append('## Other tags\n')
        for n in missing:
            parts.append(tag_section(n))
    parts.append('## Statements\n\nInside a handler, a `q:function`, or (for `q:if`, `q:loop`, `q:call`) '
                 'directly in a scene, where they run as it is entered: ' +
                 ', '.join(f'`q:{s}`' for s in STATEMENTS if s not in ('else', 'elseif')) +
                 ' (`q:else` and `q:elseif` inside a `q:if`). A `q:set` directly in a scene declares the '
                 'scene\'s state; in `q:application`, the game\'s, kept across scenes — with `saved="true"`, '
                 'between runs.\n')
    parts.append(gd_section())
    parts.append('## The games\n\nEach one is written in these tags and nothing else, and replayed '
                 'in CI from input tapes (`tests/godot/test_godot_<name>.py`).\n')
    for name, path, blurb in GAMES:
        source = (REPO / path).read_text(encoding='utf-8').rstrip('\n')
        parts.append(f'### {name}\n\n`{path}` — {blurb}.\n\n```xml\n{source}\n```\n')
    return '\n'.join(parts)


def main(argv) -> int:
    text = build()
    if '--check' in argv:
        current = OUT.read_text(encoding='utf-8') if OUT.exists() else ''
        if current != text:
            print(f'{OUT.relative_to(REPO)} is stale: run python scripts/generate-games-reference.py', file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding='utf-8')
    print(f'wrote {OUT.relative_to(REPO)}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
