"""Generate docs/showcase/index.md from the proving apps in projects/.

    python scripts/generate-showcase.py

What each app is for is written here, by hand. Everything else is measured
from the app's files: its pages and lines of .q, the q: and ui: tags it uses,
the SPEC rules its files cite (only IDs that exist in SPEC.md), the tests
that run it, and the JavaScript written for it (script files and inline
<script> blocks in its pages). tests/docs/test_showcase.py fails when the page
and this script disagree, so the numbers on the site are the apps' numbers.

The screenshots come from scripts/showcase-screenshots.py.
"""

import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PAGE = REPO / 'docs' / 'showcase' / 'index.md'
GITHUB = 'https://github.com/danielgregorio/quantum/tree/main'
MARKER = '<!-- Generated by scripts/generate-showcase.py: edit the script, not this page. -->'

APPS = [
    ('tarefas', 'Tasks (Tarefas)',
     'A task list in `ui:*`: a form validated by its action, finish and delete buttons, '
     'a filter from the address, a table that sorts and edits its cells against the '
     'schema, an edit form generated from the table, and the history of every change. '
     'The same pages run in the terminal and in a desktop window. '
     'Its content is in Portuguese; the [tutorial](../tutorial/tasks-app.md) builds '
     'it in English.',
     ['Actions and forms', 'Database', 'UI', 'Tests']),
    ('blog', 'Blog',
     'A blog over SQLite with pages that are files (`post/[slug].q`), categories, '
     'search, comments, a login and an admin area that creates and edits posts in a '
     'transaction.',
     ['Pages and routes', 'Actions and forms', 'Database', 'Authentication']),
    ('helpdesk', 'Helpdesk',
     'Open a ticket with an attachment, checked by size and type, stored outside the '
     'public folder and served only through its ticket; the team is told by mail.',
     ['Actions and forms', 'Files and mail', 'UI']),
    ('bank-transfer', 'Bank transfer',
     'Money moves between two accounts inside one transaction: an overdraft is refused '
     'before anything runs, and if any step of the transfer fails nothing moves. The '
     'page says why a transfer was refused.',
     ['Actions and forms', 'Database']),
    ('docs-assistant', 'Docs assistant',
     'Ask the Quantum guide a question: the answer comes only from the guide, cites '
     'its sources, and arrives as the model writes it. A question the guide does not '
     'cover is not sent to the model at all.',
     ['AI']),
    ('shop-agent', 'Shop agent',
     'An agent answers questions about a shop from its database through a few '
     'parameterized queries. The model never writes SQL, and every call it made is '
     'shown next to the answer.',
     ['AI', 'Database']),
    ('quantum-chat', 'Chat',
     'A small chat room: join with a name, post messages, see who is online, with the '
     'room kept in the application scope.',
     ['Actions and forms', 'How a page runs']),
]


def spec_ids():
    return set(re.findall(r'^\*\*([A-Z]+-\d+)\*\*', (REPO / 'SPEC.md').read_text(encoding='utf-8'), re.M))


def facts(app):
    root = REPO / 'projects' / app
    pages = sorted(p for p in root.rglob('*.q') if not p.name.endswith('.test.q'))
    texts = {p: p.read_text(encoding='utf-8') for p in pages}
    lines = sum(len(t.splitlines()) for t in texts.values())
    tags = Counter()
    js = sum(len(p.read_text(encoding='utf-8').splitlines()) for p in root.rglob('*.js'))
    for text in texts.values():
        code = re.sub(r'<!--.*?-->', '', text, flags=re.S)
        tags.update(re.findall(r'<((?:q|ui):[a-zA-Z-]+)\b', code))
        js += sum(len(block.strip().splitlines())
                  for block in re.findall(r'<script\b[^>]*>(.*?)</script>', code, re.S) if block.strip())
    cited = set()
    for p in root.rglob('*'):
        if p.is_file() and p.suffix in ('.q', '.yaml', '.sql'):
            cited |= set(re.findall(r'\b([A-Z]+-\d+)\b', p.read_text(encoding='utf-8', errors='ignore')))
    tests = sum(p.read_text(encoding='utf-8').count('<q:test ') for p in root.rglob('*.test.q'))
    suites = sorted(p.name for p in (REPO / 'tests' / 'apps').glob('test_*.py')
                    if p.stem == f'test_{app.replace("-", "_")}' or p.stem.startswith(f'test_{app.replace("-", "_")}_'))
    return {'pages': len(pages), 'lines': lines, 'tags': sorted(tags), 'js': js,
            'rules': sorted(cited & spec_ids(), key=lambda r: (r.split('-')[0], int(r.split('-')[1]))),
            'tests': tests, 'suites': suites}


def render():
    out = [f"""---
title: Showcase
---

# Showcase

{MARKER}

The apps that prove Quantum: each one is in the repository, runs in CI, and is
written in `.q` files with no JavaScript. The screenshots are taken from the
apps running (`scripts/showcase-screenshots.py`); the AI apps answer through a
stand-in model server, so no model is needed to reproduce them.

"""]
    for app, title, what, areas in APPS:
        f = facts(app)
        tested = []
        if f['tests']:
            tested.append(f"{f['tests']} `quantum test` tests")
        tested += [f"[`tests/apps/{s}`](https://github.com/danielgregorio/quantum/blob/main/tests/apps/{s})"
                   for s in f['suites']]
        out.append(f"""## {title}

![{title}](/showcase/{app}.png)

{what}

| | |
|---|---|
| Demonstrates | {', '.join(areas)} |
| SPEC rules it cites | {', '.join(f['rules']) or '—'} |
| Size | {f['pages']} page{'s' if f['pages'] != 1 else ''}, {f['lines']} lines of `.q`, {f['js']} lines of JavaScript |
| Tested by | {', '.join(tested)} |
| Source | [`projects/{app}`]({GITHUB}/projects/{app}) |

<details><summary>Tags it uses ({len(f['tags'])})</summary>

{' '.join(f'`{t}`' for t in f['tags'])}

</details>

""")
    return ''.join(out).rstrip() + '\n'


if __name__ == '__main__':
    PAGE.write_text(render(), encoding='utf-8', newline='\n')
    print(f'wrote {PAGE.relative_to(REPO)}')
    sys.exit(0)
