"""Generate the Reference (docs/reference/) from the code and SPEC.md — never by hand.

    python scripts/generate-reference.py          # rewrite docs/reference/
    python scripts/generate-reference.py --check  # exit 1 if a page is not current

Sources:
  tags          quantum-lsp/quantum_lsp/schema/core_tags.py (checked against the
                parser by tests/conformance/test_editor_schemas.py)
  experimental  quantum/core/tiers.py EXPERIMENTAL, with quantum-lsp's entry when it has one
  functions     quantum/core/expression_stdlib.py STDLIB (signatures and docstrings)
  cli           quantum/cli/runner.py build_parser()
  config        quantum/runtime/web_config.py (sections, keys, types, defaults)
  spec          SPEC.md, with an anchor per rule ID and the entries that cite it

tests/docs/test_reference_is_generated.py fails when the committed pages differ.
The Reference is English in every locale.
"""

import argparse
import importlib
import importlib.util
import inspect
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / 'docs' / 'reference'
sys.path.insert(0, str(REPO))

GITHUB = 'https://github.com/danielgregorio/quantum/blob/main/'
HEADER = ('<!-- Generated by scripts/generate-reference.py from the code — do not edit; '
          'run the script instead. -->\n')

# ------------------------------------------------------------------ sources


def load_lsp_schema():
    """quantum-lsp's schema package, without quantum_lsp/__init__.py (it starts the server)."""
    name = 'quantum_lsp_schema'
    if name not in sys.modules:
        folder = REPO / 'quantum-lsp' / 'quantum_lsp' / 'schema'
        spec = importlib.util.spec_from_file_location(name, folder / '__init__.py',
                                                      submodule_search_locations=[str(folder)])
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
    return sys.modules[name]


def spec_rules():
    """(sections, rules): sections [(title, [lines])] in order; rules {ID: text}."""
    text = (REPO / 'SPEC.md').read_text(encoding='utf-8')
    rules, current = {}, None
    for line in text.splitlines():
        m = re.match(r'\*\*([A-Z]+-\d+)\*\* ', line)
        if m:
            current = m.group(1)
            rules[current] = line
        elif current and line.strip():
            rules[current] += ' ' + line
        else:
            current = None
    return text, rules


SPEC_TEXT, RULES = spec_rules()
RULE_ID = re.compile(r'\b(' + '|'.join(sorted({r.split('-')[0] for r in RULES})) + r')-(\d+)\b')

# ------------------------------------------------------------------ markdown helpers


def _outside_code(text, transform):
    parts = re.split(r'(`[^`]*`)', text)
    return ''.join(p if p.startswith('`') else transform(p) for p in parts)


def link_rules(text, prefix='./spec'):
    """Known rule IDs become links to the SPEC page (never inside code)."""
    def one(part):
        return RULE_ID.sub(lambda m: f'[{m.group(0)}]({prefix}#{m.group(0)})' if m.group(0) in RULES
                           else m.group(0), part)
    return _outside_code(text, one)


def prose(text, prefix='./spec'):
    """Text for a page: `<` outside code escaped (Vue would read it), rule IDs linked."""
    return link_rules(_outside_code(text, lambda p: p.replace('<', '&lt;')), prefix)


def cell(text):
    return prose(str(text)).replace('|', '\\|').replace('\n', ' ')


def mentions(pattern):
    """The rule IDs whose text matches `pattern` (outside nothing: rules are prose with code)."""
    return [rid for rid, text in RULES.items() if re.search(pattern, text)]


def rule_links(ids, prefix='./spec'):
    return ' · '.join(f'[{r}]({prefix}#{r})' for r in ids)


def page(title, intro, body):
    return (f'---\ntitle: {title}\noutline: [2, 3]\n---\n\n{HEADER}\n# {title}\n\n{intro}\n\n'
            f'::: v-pre\n\n{body.rstrip()}\n\n:::\n')


# Backlinks for the SPEC page: rule ID -> [(label, link)]
BACKLINKS = {}


def cite(rule_ids, label, link):
    for rid in rule_ids:
        entry = (label, link)
        if entry not in BACKLINKS.setdefault(rid, []):
            BACKLINKS[rid].append(entry)

# ------------------------------------------------------------------ tags


def tag_rules(info):
    name = info.full_name
    ids = mentions(r'(?<![\w:])' + re.escape(name) + r'(?![\w-])')
    texts = [info.description] + [a.description for a in info.attributes.values()]
    for text in texts:
        ids += [m.group(0) for m in RULE_ID.finditer(text) if m.group(0) in RULES]
    return sorted(set(ids), key=lambda r: (r.split('-')[0], int(r.split('-')[1])))


def tag_section(info, parents, page_name):
    anchor = info.full_name.replace(':', '-')
    ids = tag_rules(info)
    cite(ids, f'`<{info.full_name}>`', f'./{page_name}#{anchor}')
    out = [f'<a id="{anchor}"></a>\n\n## `{info.full_name}`\n', prose(info.description) + '\n']
    if parents:
        out.append('Inside: ' + ', '.join(f'[`{p}`](#{p.replace(":", "-")})' for p in parents) + '\n')
    if info.attributes:
        out.append('| Attribute | Type | Required | Default | Values | Description |')
        out.append('|---|---|---|---|---|---|')
        for a in info.attributes.values():
            values = ', '.join(f'`{v}`' for v in a.enum_values)
            out.append(f'| `{a.name}` | {a.type.value} | {"yes" if a.required else ""} | '
                       f'{"`" + a.default + "`" if a.default else ""} | {cell(values)} | {cell(a.description)} |')
        out.append('')
    else:
        out.append('No attributes.\n')
    if info.children:
        out.append('Contains: ' + ', '.join(f'`{c}`' for c in info.children) + '\n')
    if info.examples:
        for example in info.examples:
            out.append('```xml\n' + example + '\n```\n')
    if ids:
        out.append('Specified by: ' + rule_links(ids) + '\n')
    return '\n'.join(out)


def tags_page():
    from quantum.core import tiers
    schema = load_lsp_schema()
    core = importlib.import_module(schema.__name__ + '.core_tags').CORE_AI_TAGS
    parents = {}
    for info in core.values():
        for child in info.children:
            parents.setdefault(child, []).append(info.full_name)
    groups = [('Core', [t for t in core.values() if t.name in tiers.CORE]),
              ('AI', [t for t in core.values() if t.name in tiers.AI]),
              ('Inside other tags', [t for t in core.values() if t.name not in tiers.CORE | tiers.AI])]
    body = []
    for title, tags in groups:
        body.append(f'# {title}\n' if False else f'<h1 class="reference-group">{title}</h1>\n')
        body.extend(tag_section(t, parents.get(t.full_name, []), 'tags') for t in tags)
    intro = ('The Core and AI tags ([SUPPORT_TIERS.md](' + GITHUB + 'SUPPORT_TIERS.md)): every attribute the '
             'parser accepts — a test fails when this list and the parser differ. Experimental tags are '
             'on [their own page](./experimental).')
    return page('Tags', intro, '\n'.join(body))


def experimental_page():
    from quantum.core import tiers
    schema = load_lsp_schema()
    tags = schema.QUANTUM_TAGS
    body = ['::: warning Experimental\nThese tags exist and run, with no stability promise: they may change or '
            'go away in any release, and the SPEC does not specify them (SUPPORT_TIERS.md).\n:::\n']
    described = sorted(n for n in tiers.EXPERIMENTAL if f'q:{n}' in tags)
    bare = sorted(n for n in tiers.EXPERIMENTAL if f'q:{n}' not in tags)
    body.extend(tag_section(tags[f'q:{n}'], [], 'experimental') for n in described)
    if bare:
        body.append('## Without a schema\n')
        body.append('The editor schema does not describe these yet: ' +
                    ', '.join(f'`q:{n}`' for n in bare) + '.\n')
    body.append('## Application types\n')
    body.append('`q:application type=` — Laboratory: ' + ', '.join(f'`{t}`' for t in sorted(tiers.LAB_APP_TYPES)) +
                '; Experimental: ' + ', '.join(f'`{t}`' for t in sorted(tiers.EXPERIMENTAL_APP_TYPES)) +
                ' (APP-1). A web application is pages in `components/`.\n')
    return page('Experimental tags', 'Tags outside the Core and the AI.', '\n'.join(body))

# ------------------------------------------------------------------ functions

BUILTINS = {
    'abs': ('abs(x)', 'The absolute value.'),
    'min': ('min(a, b, …) / min(list)', 'The smallest of the values.'),
    'max': ('max(a, b, …) / max(list)', 'The largest of the values.'),
    'int': ('int(x)', 'The value as a whole number (text or a number; a fraction is cut).'),
    'float': ('float(x)', 'The value as a number with decimals.'),
    'str': ('str(x)', 'The value as text.'),
}


def functions_page():
    from quantum.core import expression_stdlib
    source = inspect.getsource(expression_stdlib)
    block = source[source.index('STDLIB = {'):]
    block = block[:block.index('\n}') + 2]
    groups, current = [], None
    for line in block.splitlines()[1:]:
        comment = re.match(r'\s*#\s*(.+)', line)
        entry = re.match(r"\s*'(\w+)':", line)
        if comment:
            current = (comment.group(1).strip().capitalize(), [])
            groups.append(current)
        elif entry:
            current[1].append(entry.group(1))
    body = []
    for title, names in groups:
        body.append(f'## {prose(title)}\n')
        for name in names:
            func = expression_stdlib.STDLIB[name]
            if name in BUILTINS:
                signature, description = BUILTINS[name]
            else:
                params = str(inspect.signature(func)).split(' -> ')[0]
                params = re.sub(r': [\w\[\], .]+?(?=[,=)])', '', params)
                signature = f'{name}{params}'
                description = inspect.getdoc(func).split('\n\n')[0].replace('\n', ' ')
            ids = [m.group(0) for m in RULE_ID.finditer(description) if m.group(0) in RULES]
            ids = sorted(set(ids + mentions(r'(?<![\w.])' + re.escape(name) + r'\(')),
                         key=lambda r: (r.split('-')[0], int(r.split('-')[1])))
            anchor = f'fn-{name.lower()}'
            cite(ids, f'`{name}()`', f'./functions#{anchor}')
            body.append(f'<a id="{anchor}"></a>\n\n### `{signature}`\n\n{prose(description)}\n')
            if ids:
                body.append('Specified by: ' + rule_links(ids) + '\n')
    intro = ('The functions an expression can call, by name (`split(t, " ")`, not `t.split(" ")` — '
             '[EXPR-10](./spec#EXPR-10)). Operators and the rest of the expression language are in '
             '[the SPEC](./spec#EXPR-1).')
    return page('Expression functions', intro, '\n'.join(body))

# ------------------------------------------------------------------ cli


def _subcommands(parser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            helps = {a.dest: a.help for a in action._choices_actions}
            for name, sub in action.choices.items():
                yield name, helps.get(name), sub


def _arguments(parser):
    rows = []
    for action in parser._actions:
        if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction, argparse._VersionAction)):
            continue
        name = ', '.join(action.option_strings) if action.option_strings else action.dest
        if not action.option_strings and action.nargs in ('?', '*'):
            name = f'[{name}]'
        default = '' if action.default in (None, False, argparse.SUPPRESS) or action.option_strings == [] and \
            action.nargs is None else action.default
        if isinstance(default, list):
            default = ' '.join(map(str, default))
        choices = ', '.join(f'`{c}`' for c in action.choices) if action.choices else ''
        rows.append(f'| `{name}` | {cell(action.help or "")} | {"`" + str(default) + "`" if default != "" else ""} '
                    f'| {choices} |')
    return rows


def cli_section(path, help_text, parser, depth):
    command = 'quantum ' + ' '.join(path)
    anchor = 'cli-' + '-'.join(path)
    ids = mentions(r'`' + re.escape(command) + r'[`\s]')
    cite(ids, f'`{command}`', f'./cli#{anchor}')
    out = [f'<a id="{anchor}"></a>\n\n{"#" * min(depth, 4)} `{command}`\n']
    if help_text:
        out.append(prose(help_text[0].upper() + help_text[1:]) + '.\n' if not help_text.endswith('.')
                   else prose(help_text) + '\n')
    rows = _arguments(parser)
    if rows:
        out.append('| Argument | Meaning | Default | Values |\n|---|---|---|---|')
        out.extend(rows)
        out.append('')
    if ids:
        out.append('Specified by: ' + rule_links(ids) + '\n')
    for name, sub_help, sub in _subcommands(parser):
        out.append(cli_section(path + [name], sub_help, sub, depth + 1))
    return '\n'.join(out)


def cli_page():
    from quantum.cli.runner import build_parser
    parser, _ = build_parser()
    body = ['| Option | Meaning |\n|---|---|\n| `--version` | The installed version. |\n| `-h, --help` | '
            'The commands and their options. |\n']
    for name, help_text, sub in _subcommands(parser):
        body.append(cli_section([name], help_text, sub, 2))
    intro = ('The `quantum` command. Every command takes `-h` / `--help`. The Guide explains the everyday '
             'ones: [CLI commands](../tools/cli).')
    return page('Command line', intro, '\n'.join(body))

# ------------------------------------------------------------------ config


def config_page():
    # A copy of the module, loaded from its file: the test suite redirects the
    # default paths of the imported one (no test writes into the repository).
    spec = importlib.util.spec_from_file_location('web_config_as_shipped',
                                                  REPO / 'quantum' / 'runtime' / 'web_config.py')
    web_config = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(web_config)
    defaults = web_config.ConfigLoading()._load_config(str(REPO / 'does-not-exist.yaml'))
    known = dict(web_config._KNOWN_KEYS)
    known.setdefault('datasources', set()).update(web_config._DATASOURCE_KEYS)
    typed = {}
    for (section, key), kind in web_config._TYPED.items():
        typed[(section, key)] = kind.__name__
        known.setdefault(section, set()).add(key)
    for section, key in re.findall(r'`(\w+)\.(\w+)[`:]', SPEC_TEXT):
        if section in web_config._KNOWN_SECTIONS and key.islower():
            known.setdefault(section, set()).add(key)
    body = []
    for section in sorted(web_config._KNOWN_SECTIONS):
        anchor = f'cfg-{section}'
        ids = mentions(r'(?<![\w.])`?' + re.escape(section) + r'[.:`]')
        cite(ids, f'`{section}:`', f'./config#{anchor}')
        body.append(f'<a id="{anchor}"></a>\n\n## `{section}`\n')
        if section == 'datasources':
            body.append('A map of datasource name → its keys (DB-7): `datasources: {db: {driver: sqlite, '
                        'database: ./app.db}}`.\n')
        keys = sorted(known.get(section, ()))
        if keys:
            body.append('| Key | Type | Default | Rules |\n|---|---|---|---|')
            for key in keys:
                value = (defaults.get(section) or {}).get(key) if isinstance(defaults.get(section), dict) else None
                key_ids = mentions(r'`' + re.escape(f'{section}.{key}') + r'`') + \
                    mentions(r'(?<![\w.])`' + re.escape(key) + r'`') if section in web_config._KNOWN_KEYS else \
                    mentions(r'`' + re.escape(f'{section}.{key}') + r'`')
                key_ids = sorted(set(key_ids), key=lambda r: (r.split('-')[0], int(r.split('-')[1])))
                cite(key_ids, f'`{section}.{key}`', f'./config#{anchor}')
                shown = '' if value is None or key in ('secret_key',) else f'`{value}`'
                body.append(f'| `{key}` | {typed.get((section, key), "")} | {shown} | {rule_links(key_ids)} |')
            body.append('')
        if section in web_config._KNOWN_KEYS:
            body.append('Another key in this section is warned about when the configuration is loaded '
                        '([CFG-2](./spec#CFG-2), [CFG-3](./spec#CFG-3)).\n')
        elif section != 'datasources':
            body.append('Accepted; its keys are not checked.\n')
        if ids:
            body.append('Specified by: ' + rule_links(ids) + '\n')
    intro = ('`quantum.config.yaml`, next to the app. `${NAME}` in any value is the environment variable '
             '`NAME` ([CFG-1](./spec#CFG-1)); a section not listed here is warned about.')
    return page('Configuration', intro, '\n'.join(body))

# ------------------------------------------------------------------ spec


def spec_page():
    """SPEC.md by paragraph (code spans wrap across lines): an anchor per rule, its backlinks after it."""
    blocks, block, fenced = [], [], False
    for line in SPEC_TEXT.splitlines()[1:]:           # the page has its own title
        if line.startswith('```'):
            fenced = not fenced
        if not line.strip() and not fenced:
            if block:
                blocks.append('\n'.join(block))
            block = []
        else:
            block.append(line)
    if block:
        blocks.append('\n'.join(block))
    out = []
    for text in blocks:
        if text.startswith('```'):
            out.append(text)
            continue
        m = re.match(r'\*\*([A-Z]+-\d+)\*\* ', text)
        if not m:
            out.append(prose(text, prefix=''))
            continue
        rid = m.group(1)
        out.append(f'<a id="{rid}"></a>**[{rid}](#{rid})** ' + prose(text[m.end():], prefix=''))
        out.extend(_backlinks(rid))
    body = '\n\n'.join(out)
    body = re.sub(r'\]\(((?!https?:|#|\./|\.\./)[\w./-]+\.md)\)', lambda m: f']({GITHUB}{m.group(1)})', body)
    intro = ('The specification of the Core and the AI, rule by rule: each rule has an anchor '
             '(`spec#EXPR-14`) and lists the Reference entries that cite it. Source: '
             f'[SPEC.md]({GITHUB}SPEC.md).')
    return page('Specification', intro, body)


def _backlinks(rid):
    import html
    entries = BACKLINKS.get(rid)
    if not entries:
        return []
    return ['<p class="spec-cited">Referenced by: ' +
            ' · '.join(f'<a href="{link}"><code>{html.escape(label.strip("`"))}</code></a>'
                       for label, link in entries) + '</p>']

# ------------------------------------------------------------------ index


def index_page(counts):
    body = f"""| Page | What it lists |
|---|---|
| [Tags](./tags) | The {counts['tags']} Core and AI tags: attributes, types, values, defaults, rules |
| [Expression functions](./functions) | The {counts['functions']} functions an expression can call |
| [Command line](./cli) | `quantum` and its commands, options and defaults |
| [Configuration](./config) | The sections and keys of `quantum.config.yaml` |
| [Specification](./spec) | The {counts['rules']} rules of the SPEC, each with an anchor |
| [Experimental tags](./experimental) | Tags outside the Core and the AI |
"""
    intro = ('Generated from the code and the SPEC on every change: what is here is what the parser, '
             'the runtime and the command line do. The Guide explains; this lists.')
    return page('Reference', intro, body)


def pages():
    """{file name: content} — in dependency order: SPEC backlinks come from the other pages."""
    BACKLINKS.clear()
    result = {
        'tags.md': tags_page(),
        'experimental.md': experimental_page(),
        'functions.md': functions_page(),
        'cli.md': cli_page(),
        'config.md': config_page(),
    }
    result['spec.md'] = spec_page()
    from quantum.core.expression_stdlib import STDLIB
    schema = load_lsp_schema()
    core = importlib.import_module(schema.__name__ + '.core_tags').CORE_AI_TAGS
    result['index.md'] = index_page({'tags': len(core), 'functions': len(STDLIB), 'rules': len(RULES)})
    return result


def main():
    generated = pages()
    if '--check' in sys.argv:
        stale = [name for name, text in generated.items()
                 if not (OUT / name).exists() or (OUT / name).read_text(encoding='utf-8') != text]
        if stale:
            print('not current:', ', '.join(stale), '— run python scripts/generate-reference.py')
            return 1
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in generated.items():
        (OUT / name).write_text(text, encoding='utf-8', newline='\n')
    print('wrote', len(generated), 'pages to', OUT.relative_to(REPO))
    return 0


if __name__ == '__main__':
    sys.exit(main())
