#!/usr/bin/env python3
"""
dungeon-quest - Generated by Quantum Terminal Engine
Run: python dungeon_quest.py
Requires: pip install textual
"""

from textual.app import App, ComposeResult
from textual.containers import Horizontal, Vertical
from textual.widgets import (
    Header, Footer, Static, Button, Input,
    DataTable, ProgressBar, Tree, RichLog,
    TabbedContent, TabPane, OptionList,
)
from textual.binding import Binding
from textual.reactive import reactive



class dungeon_questApp(App):
    TITLE = "dungeon-quest"
    CSS = """#room-desc { height: 1fr; border: solid #666; padding: 1 2; }
    #inventory-panel { width: 30; border: solid yellow; }
"""

    BINDINGS = [
        Binding("q", "quit", "Quit"),
    ]

    current_room = reactive("entrance")
    inventory = reactive([])
    hp = reactive(100.0)

    def compose(self) -> ComposeResult:
        """Build the widget tree."""
        yield Header()
        with Horizontal():
            with Vertical(id="room-desc"):
                yield Static("You stand at the entrance of a dark dungeon...", id="room-text")
            with Vertical(id="inventory-panel"):
                yield Static("[bold red]HP: {hp}/100[/]", id="hp-display")
                yield Tree("Backpack", id="inv-tree")
        yield RichLog(max_lines=50, id="action-log")
        yield Input(placeholder="go north, take key, look...", id="cmd")
        yield Footer()

    def on_input_submitted(self, event: Input.Submitted):
        """Handle input submit events."""
        if event.input.id == "cmd":
            self.action_process_command()

    def process_command(self):
        self.placeholder = "process_command action"

    def action_process_command(self):
        """Action: process_command"""
        self.process_command()

if __name__ == "__main__":
    app = dungeon_questApp()
    app.run()
