#!/usr/bin/env python3
"""
file-browser - Generated by Quantum Terminal Engine
Run: python file_browser.py
Requires: pip install textual
"""

from textual.app import App, ComposeResult
from textual.containers import Horizontal, Vertical
from textual.widgets import (
    Header, Footer, Static, Button, Input,
    DataTable, ProgressBar, Tree, RichLog,
    TabbedContent, TabPane, OptionList,
)
from textual.binding import Binding
from textual.reactive import reactive



class file_browserApp(App):
    TITLE = "file-browser"
    CSS = """#file-tree { width: 40; border: solid green; }
    #preview { height: 1fr; border: solid #444; }
"""

    BINDINGS = [
        Binding("q", "quit", "Quit"),
        Binding("r", "refresh_tree", "Refresh"),
    ]

    def compose(self) -> ComposeResult:
        """Build the widget tree."""
        yield Header()
        with Horizontal():
            yield Tree(".", id="file-tree")
            with Vertical(id="preview"):
                yield Static("Select a file...", id="file-content")
        yield Footer()

    def action_refresh_tree(self):
        """Action: refresh_tree"""
        self.notify("Action: refresh_tree")

if __name__ == "__main__":
    app = file_browserApp()
    app.run()
