#!/usr/bin/env python3
"""
server-dashboard - Generated by Quantum Terminal Engine
Run: python server_dashboard.py
Requires: pip install textual
"""

from textual.app import App, ComposeResult
from textual.containers import Horizontal, Vertical
from textual.widgets import (
    Header, Footer, Static, Button, Input,
    DataTable, ProgressBar, Tree, RichLog,
    TabbedContent, TabPane, OptionList,
)
from textual.binding import Binding
from textual.reactive import reactive



class server_dashboardApp(App):
    TITLE = "server-dashboard"
    CSS = """#cpu-panel { border: solid green; height: 1fr; }
    #log-panel { border: solid yellow; height: 2fr; }
"""

    BINDINGS = [
        Binding("q", "quit", "Quit"),
        Binding("r", "refresh_data", "Refresh"),
    ]

    refresh_count = reactive(0.0)
    cpu_pct = reactive(42.0)

    def compose(self) -> ComposeResult:
        """Build the widget tree."""
        yield Header(show_clock=True)
        with Horizontal():
            with Vertical(id="cpu-panel"):
                yield ProgressBar(total=100.0, id="cpu-bar")
                yield Static("{cpu_pct}% used")
        with Vertical(id="log-panel"):
            yield DataTable(id="proc-table", zebra_stripes=True)
        yield Footer()

    def on_mount(self):
        """Set up timers on app mount."""
        self.set_interval(5.0, self.action_refresh_data)

    def action_refresh_data(self):
        """Action: refresh_data"""
        self.notify("Action: refresh_data")

if __name__ == "__main__":
    app = server_dashboardApp()
    app.run()
