"""`quantum admin` — serve the Quantum Admin (quantum_admin/components/admin).

The admin is a Quantum app: .q screens over declared services. This command
writes its configuration into a data folder and starts the same server as
`quantum start`, so nothing has to be set up by hand.

    quantum admin                      # data in ./.quantum-admin, projects under ./
    quantum admin --data quantum_admin # the repository's own admin data

The data folder holds the admin database, its settings (connectors, global
settings, process PIDs) and the generated config. Paths of projects are
relative to the folder the command runs in (--root to change it).
"""

import os
import secrets
from pathlib import Path

MODULES = [
    "quantum_admin.services.auth",
    "quantum_admin.services.projects",
    "quantum_admin.services.yaml_import",
    "quantum_admin.services.connectors",
    "quantum_admin.services.settings",
    "quantum_admin.services.components",
    "quantum_admin.services.apps",
    "quantum_admin.services.repository",
]

INSTALL_HINT = 'pip install "quantum-framework[admin]"'


def create_admin_parser(subparsers):
    parser = subparsers.add_parser('admin', help='Start the Quantum Admin')
    parser.add_argument('--port', type=int, default=8090, help='Port (default 8090)')
    parser.add_argument('--data', default='.quantum-admin',
                        help='Folder for the admin database and settings (default ./.quantum-admin)')
    parser.add_argument('--root', default='.',
                        help='Folder the project paths are relative to (default: current folder)')
    return parser


def missing_dependencies():
    """Names of the [admin] extra's packages that do not import."""
    missing = []
    for module, package in (("sqlalchemy", "SQLAlchemy"), ("jwt", "PyJWT"),
                           ("cryptography", "cryptography")):
        try:
            __import__(module)
        except ImportError:
            missing.append(package)
    return missing


def _package() -> Path:
    import quantum_admin
    return Path(quantum_admin.__file__).resolve().parent


def screens_folder() -> Path:
    return _package() / "components"


def assets_folder() -> Path:
    """The screens' CSS and JS, served under /static/."""
    return _package() / "assets"


def _secret(file: Path) -> str:
    """A key kept in the data folder, so sessions survive a restart."""
    if file.exists():
        return file.read_text(encoding="utf-8").strip()
    key = secrets.token_hex(32)
    file.write_text(key, encoding="utf-8")
    try:
        file.chmod(0o600)
    except OSError:
        pass
    return key


def prepare(data: str, root: str, port: int) -> Path:
    """Create the data folder, point the admin at it, write the config. Returns its path."""
    import yaml

    folder = Path(data).resolve()
    (folder / "settings").mkdir(parents=True, exist_ok=True)

    # Read by quantum_admin.core at import time, so set before any import.
    os.environ["QUANTUM_ADMIN_DATABASE_URL"] = f"sqlite:///{(folder / 'quantum_admin.db').as_posix()}"
    os.environ["QUANTUM_ADMIN_SETTINGS_DIR"] = str(folder / "settings")
    os.environ["QUANTUM_ADMIN_ROOT"] = str(Path(root).resolve())
    os.environ.setdefault("JWT_SECRET_KEY", _secret(folder / "jwt_secret"))

    config = folder / "quantum.config.yaml"
    config.write_text(
        "# Generated by `quantum admin` on every start; edits are overwritten.\n" +
        yaml.safe_dump({
            "server": {"host": "127.0.0.1", "port": port, "reload": False, "debug": False},
            "paths": {"components": screens_folder().as_posix(),
                      "static": assets_folder().as_posix(),
                      "uploads": (folder / "uploads").as_posix(),
                      "logs": (folder / "logs").as_posix()},
            "security": {"login_url": "/admin/login", "secret_key": _secret(folder / "session_secret")},
            "logging": {"level": "WARNING", "console": True, "file": False},
            "services": MODULES,
        }, sort_keys=False),
        encoding="utf-8")
    return config


def handle_admin(args) -> int:
    missing = missing_dependencies()
    if missing:
        print(f"[ERROR] The admin needs {', '.join(missing)}. Install with:\n  {INSTALL_HINT}")
        return 1

    config = prepare(args.data, args.root, args.port)

    from quantum.runtime.web_server import QuantumWebServer
    from quantum_admin.core.auth_service import get_auth_service

    # Created now, not at the first login, so a generated password is printed
    # before the URL instead of in the middle of the request log.
    get_auth_service()
    print(f"\n  Quantum Admin: http://127.0.0.1:{args.port}/admin"
          f"\n  data: {config.parent}\n")

    server = QuantumWebServer(str(config))
    server.PID_FILE = str(config.parent / "admin.pid")
    return server.start() or 0
